### ISSUE TITLE
`onModuleInit()` not called when microservice transport needs a config in the bootstrap function 

### ISSUE THREAD

**Issue by sprijk** [nestjs/nest#12042] opened 2023-07-18 15:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In the bootstrap function of a microservice I need access to the `ConfigService` to configure the Kafka brokers.

However, if an application is started like this:

```ts
async function bootstrap() {
  const appConfig = await NestFactory.create(AppModule);
  const config = appConfig.get(ConfigService);

  const app = appConfig.connectMicroservice<MicroserviceOptions>({
    transport: Transport.KAFKA,
    options: {
      client: {
        brokers: config.get<string[]>('kafka.brokers'),
      },
      consumer: {
        groupId: 'some-consumer-group-id',
      },
    },
  });

  await app.listen();
}
bootstrap();
```
Then, the lifecycle method `onModuleInit()` is never triggered.

However, when I use the `NestFactory.createMicroservice()` directly - without using an instance of the `ConfigService` - the lifecycle methods works as expected.

Is there a way to use an instance on the ConfigService without instantiating a separate `INestApplication` first?

### Minimum reproduction code

https://github.com/sprijk/nestjs-microservice-lifecycle-issue

### Steps to reproduce

1. npm run start

See that the `app.controller.ts`'s `onModuleInit()` function is never called.

### Expected behavior

The lifecycle methods are called.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.0

### Packages versions

```json
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/config": "^3.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/microservices": "^10.1.0",
    "@nestjs/platform-express": "^10.0.0",
    "kafkajs": "^2.2.4",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.59.11",
    "@typescript-eslint/parser": "^5.59.11",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "^29.5.0",
    "prettier": "^2.8.8",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  }
```

### Node.js version

18.16.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment] 2023-07-18 16:10
I can't get past the kafka error on startup. Is there something else I need to do, other than call `docker compose up -d`?

**Comment by sprijk** [comment] 2023-07-18 18:10
Try to restart run `npm start`, or `docker-compose down` and `up`, or manually create the `hello` topic via http://localhost:8080 😋

**Comment by jmcdo29** [comment] 2023-07-18 18:18
Nope. The docker compose just won't start up. It seems to keep core dumping. Without being able to start kafka in the first place I won't be able to test your repository. Please ensure your minimum reproduction works on Linux or provide more explicit instructions on how to test this

**Comment by sprijk** [comment] 2023-07-18 18:23
Before the `docker-compose up`, I've made sure to delete any containers and their volumes involved. This what I get on a fresh `docker-compose up`:
```
$ npm start

> bla@0.0.1 start
> nest start

[Nest] 17615  - 07/18/2023, 8:21:18 PM     LOG [NestFactory] Starting Nest application...
[Nest] 17615  - 07/18/2023, 8:21:18 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +7ms
[Nest] 17615  - 07/18/2023, 8:21:18 PM     LOG [InstanceLoader] AppModule dependencies initialized +0ms
[Nest] 17615  - 07/18/2023, 8:21:18 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 17615  - 07/18/2023, 8:21:18 PM   ERROR [ServerKafka] ERROR [Connection] Response Metadata(key: 3, version: 6) {"timestamp":"2023-07-18T18:21:18.772Z","logger":"kafkajs","broker":"localhost:9092","clientId":"nestjs-consumer-server","error":"There is no leader for this topic-partition as we are in the middle of a leadership election","correlationId":1,"size":79}
[Nest] 17615  - 07/18/2023, 8:21:19 PM     LOG [ServerKafka] INFO [Consumer] Starting {"timestamp":"2023-07-18T18:21:19.131Z","logger":"kafkajs","groupId":"some-consumer-group-id-server"}
[Nest] 17615  - 07/18/2023, 8:21:19 PM   ERROR [ServerKafka] ERROR [Connection] Response GroupCoordinator(key: 10, version: 2) {"timestamp":"2023-07-18T18:21:19.166Z","logger":"kafkajs","broker":"localhost:9092","clientId":"nestjs-consumer-server","error":"The group coordinator is not available","correlationId":3,"size":55}
[Nest] 17615  - 07/18/2023, 8:21:19 PM   ERROR [ServerKafka] ERROR [Connection] Response GroupCoordinator(key: 10, version: 2) {"timestamp":"2023-07-18T18:21:19.441Z","logger":"kafkajs","broker":"localhost:9092","clientId":"nestjs-consumer-server","error":"The group coordinator is not available","correlationId":4,"size":55}
[Nest] 17615  - 07/18/2023, 8:21:20 PM     LOG [ServerKafka] INFO [ConsumerGroup] Consumer has joined the group {"timestamp":"2023-07-18T18:21:20.034Z","logger":"kafkajs","groupId":"some-consumer-group-id-server","memberId":"nestjs-consumer-server-c19cb4e3-e470-4588-ac1a-398c6b669465","leaderId":"nestjs-consumer-server-c19cb4e3-e470-4588-ac1a-398c6b669465","isLeader":true,"memberAssignment":{"hello":[0]},"groupProtocol":"RoundRobinAssigner","duration":902}
[Nest] 17615  - 07/18/2023, 8:21:20 PM     LOG [NestMicroservice] Nest microservice successfully started +1ms
```

**Comment by sprijk** [comment] 2023-07-18 18:26
When I produce a message (e.g. `Hello there, from Kafka UI!`) in Kafka UI, I see this `console.log` appear:
`message Hello there, from Kafka UI!`

**Comment by sprijk** [comment] 2023-07-18 18:28
A workaround for not using `docker-compose` would be to use any other working single-instance Kafka set-up with its broker on `localhost:9092`.

**Comment by jmcdo29** [comment] 2023-07-18 18:33
For the third time, your reproduction does not start, and thus I cannot test your error. Here's a snapshot of the logs from compose:

<details>

<summary>Kafka log errors</summary>

```
nestjs-microservice-lifecycle-issue-kafka-1     |
nestjs-microservice-lifecycle-issue-kafka-1     | Transformed zookeeper.properties:
nestjs-microservice-lifecycle-issue-kafka-1     |
nestjs-microservice-lifecycle-issue-kafka-1     | dataDir=/var/lib/kafka/zk
nestjs-microservice-lifecycle-issue-kafka-1     | clientPort=2181
nestjs-microservice-lifecycle-issue-kafka-1     | maxClientCnxns=0
nestjs-microservice-lifecycle-issue-kafka-1     | autopurge.purgeInterval=0
nestjs-microservice-lifecycle-issue-kafka-1     |
nestjs-microservice-lifecycle-issue-kafka-1     |
nestjs-microservice-lifecycle-issue-kafka-1     | library initialization failed - unable to allocate file descriptor table - out of memory
```

</details>

I'll be happy to look into this **when** you provide a minimum reproduction that _actually_ starts and reproduces the error.

**Comment by sprijk** [comment] 2023-07-18 20:54
All cool, I've narrowed it down a bit more. The behavior I'd like to demonstrate is also present in my latest commit when using the transport `Transport.TCP`:

```ts
async function bootstrap() {
  const show_the_bug = true; // ← change this to `false` to see the alternate approach work

  if (show_the_bug) {
    // current approach → onModuleInit() in `app.controller.ts` is never called
    const appConfig = await NestFactory.create(AppModule);
    const config = appConfig.get(ConfigService);

    const app = appConfig.connectMicroservice<MicroserviceOptions>({
      transport: Transport.TCP,
      options: {
        port: config.get<number>('tcp.port'),
      },
    });

    await app.listen();
  } else {
    // This works:
    // alternate approach without `ConfigService` instance and hardcoding the tcp port → onModuleInit() in `app.controller.ts` is now indeed triggered
    const app = await NestFactory.createMicroservice(AppModule, {
      transport: Transport.TCP,
      options: {
        port: 3000,
      },
    });

    await app.listen();
  }
}

bootstrap();
```

**Comment by jmcdo29** [comment] 2023-07-18 20:58
Thank you for slimming down the reproduction to remove the extra dependencies. With the TCP approach you are showing, I can confirm I see the same behavior. I'll re-open this and and start looking through it as I can

**Comment by kamilmysliwiec** [comment] 2023-07-19 07:22
Because `connectMicroservice` returns a reference to the underlying microservice consumer attached to the application instance. When creating a hybrid application, you should operate on the `app` reference returned by the `NestFactory#create` (not `connectMicroservice`) - as this is your application instance and it must be initialized (through either `init()` or `listen()`) to trigger lifecycle hooks.

This is shown in the docs:

![image](https://github.com/nestjs/nest/assets/23244943/1c97526c-3380-466b-89ba-0033a7e74e37)

Moreover, in most cases, you don't even need the reference to the `microservice` so it really boils down to this:

```typescript
const app = await NestFactory.create(AppModule);
app.connectMicroservice<MicroserviceOptions>({
  transport: Transport.TCP,
}); // note missing "const microservice = assignment"

await app.startAllMicroservices();
await app.listen(3001);
```

> Is there a way to use an instance on the ConfigService without instantiating a separate INestApplication first?

BTW you should never instantiate 2 separate Nest apps.

Duplicate of https://github.com/nestjs/nest/issues/2343

**Closed by kamilmysliwiec** 2023-07-19 07:22 UTC
Labels: needs triage
