### ISSUE TITLE
HttpStatus enum is not bundled correctly

### ISSUE THREAD

**Issue by skrtheboss** [nestjs/nest#7150] opened 2021-05-18 08:06 UTC
## Regression
http-status.enum.js is empty in [v7.6.16](https://unpkg.com/browse/@nestjs/common@7.6.16/enums/http-status.enum.js)

## Expected behavior/code
@nestjs/common should boundle HttpStatus code correctly like in [v7.6.15](https://unpkg.com/browse/@nestjs/common@7.6.15/enums/http-status.enum.js)

## Environment
Nest version: 7.6.15 -> 7.6.16

**Comment by ericmorand** [comment] 2021-05-18 08:11
It leads to the following error:

```
TypeError: Cannot read property 'OK' of undefined
    at RouterResponseController.getStatusByMethod ([...]/node_modules/@nestjs/core/router/router-response-controller.js:42:44)
```

**Comment by JaeWangL** [comment] 2021-05-18 08:39
Same issue with `7.6.16`

**Comment by kamilmysliwiec** [comment] 2021-05-18 08:43
Fixed in 7.6.17

**Closed by kamilmysliwiec** 2021-05-18 08:43 UTC
Labels: needs triage, type: bug :sob:

**Comment by ericmorand** [comment] 2021-05-18 08:51
@kamilmysliwiec , can you please update us on how the issue was able to go to production release? We are a bit concerned by the fact that a patch could create a regression without being detected by the test suite.

**Comment by vegerot** [comment] 2021-09-23 20:24
whoops.  I made this commit.  Didn't realize people were using the enum like _[this](https://github.com/nestjs/nest/issues/7150#issuecomment-842957062)!_ D: 

To be fair...BECAUSE I hadn't foreseen this enum was being used like [this](https://github.com/nestjs/nest/issues/7150#issuecomment-842957062), is just another reason that tests are so important

**Comment by vegerot** [comment] 2021-09-23 20:31
@kamilmysliwiec I'm disappointed 8ef6c42 didn't include a regression test for [this](https://github.com/nestjs/nest/issues/7150#issuecomment-842957062).  What's to stop someone from just raising another perf PR like #6979 again?
