### ISSUE TITLE
How to obtain the consumer instance for Kafka transport?

### ISSUE THREAD

**Issue by raymondsze** [nestjs/nest#3961] opened 2020-01-29 13:50 UTC
## Bug Report
When using autoCommit = false, we need a way to commit manually which require `consumer.commitOffset`.

But seems I'm not able to obtain the consumer instance created inside ServerKafka.

## Current behavior
Not able to obtain the consumer instance created inside ServerKafka.

## Expected behavior
Should able to obtain the consumer instance created inside ServerKafka.

## Possible Solution
No idea right now

## Environment

<pre><code>
Nest version: ^6.0.0

 
For Tooling issues:
- Node version: 10  
- Platform: Mac 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment] 2020-02-02 11:30
Duplicate of https://github.com/nestjs/nest/issues/3913

**Closed by kamilmysliwiec** 2020-02-02 11:30 UTC
Labels: scope: microservices, type: question 🙌

**Comment by krukru** [comment] 2020-03-27 14:08
Hey @kamilmysliwiec, I think it is not a duplicate. #3913 refers to ClientKafka, while this question is about the ServerKafka client. To be able to commit manually, one has to get the consumer instance from the ServerKafka - which does not seem to be possible at the moment. Thanks :)

**Comment by bradsheppard** [comment] 2021-07-12 03:05
@raymondsze @krukru  You can achieve this by creating a slight modification of the built-in Kafka transporter. Create a new class as follows:

```typescript
import { KafkaContext, KafkaHeaders, ServerKafka } from '@nestjs/microservices';
import { EachMessagePayload } from '@nestjs/microservices/external/kafka.interface';
import { NO_MESSAGE_HANDLER } from '@nestjs/microservices/constants';
import { Observable } from 'rxjs';
import { KafkaParser } from '@nestjs/microservices/helpers/kafka-parser'

export default class KafkaCustomerTransporter extends ServerKafka {
	public async handleMessage(payload: EachMessagePayload) {
		const channel = payload.topic;
		const rawMessage = KafkaParser.parse(Object.assign(payload.message, {
			topic: payload.topic,
			partition: payload.partition,
		}));
		const headers = (rawMessage.headers as unknown) as Record<string, any>;
		const correlationId = headers[KafkaHeaders.CORRELATION_ID];
		const replyTopic = headers[KafkaHeaders.REPLY_TOPIC];
		const replyPartition = headers[KafkaHeaders.REPLY_PARTITION];

		const packet = this.deserializer.deserialize(rawMessage, { channel });
		const kafkaContext = new KafkaContext([
			rawMessage,
			payload.partition,
			payload.topic,
		]);
		// if the correlation id or reply topic is not set
		// then this is an event (events could still have correlation id)
		if (!correlationId || !replyTopic) {
			const result = this.handleEvent(packet.pattern, packet, kafkaContext);
			const commitMessage = {
				topic: payload.topic,
				partition: payload.partition,
				offset: (parseInt(rawMessage.offset) + 1).toString()
			}
			await this.consumer.commitOffsets([commitMessage])
			return result
		}

		const publish = this.getPublisher(
			replyTopic,
			replyPartition,
			correlationId,
		);
		const handler = this.getHandlerByPattern(packet.pattern);
		if (!handler) {
			return publish({
				id: correlationId,
				err: NO_MESSAGE_HANDLER,
			});
		}

		const response$ = this.transformToObservable(
			await handler(packet.data, kafkaContext),
		) as Observable<any>;
		response$ && this.send(response$, publish);
                const commitMessage = {
		        topic: payload.topic,
		        partition: payload.partition,
		        offset: (parseInt(rawMessage.offset) + 1).toString()
	        }
	        await this.consumer.commitOffsets([commitMessage])
	}
}

```

Then load it as follows:

```typescript
const app = await NestFactory.create(AppModule);
app.connectMicroservice({
	strategy: new KafkaCustomerTransporter({
		subscribe: {
			fromBeginning: true
		},
		client: {
			brokers: ['queue-kafka-bootstrap:9092'],
		},
		consumer: {
			groupId: 'consumer-group-id',
		},
		run: {
			autoCommit: false,
		},
	})
});
```
Notice the call to `commitOffsets` in this new class. That should take care of your use-case. Unfortunately I can't see any other way to do this because the `Consumer` isn't exposed externally.
