### ISSUE TITLE
Console log the localhost URL with port when run the application

### ISSUE THREAD

**Issue by chauhankiran** [nestjs/nest#10382] opened 2022-10-09 09:01 UTC
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I followed the steps mentioned in Docs/Installation section and created the application using `nest new` command. 

When I run the application using `npm run start` command, it shows that the application is complied and running. But, it take a time to figure out that the application is running at port 3000 (Yes, I haven't read the documentation further after creating a project command).

### Describe the solution you'd like

Should be possible to print the localhost URL in terminal before/after compilation logs that the application is running at http://localhost:3000 ?

### Teachability, documentation, adoption, migration strategy

This will actually help in teaching as log will give a clear indication that application is running and at port 3000.

### What is the motivation / use case for changing the behavior?

Printing the localhost URL in log is pretty much every where in almost all popular framework such as React, Angular, Rails, Laravel, etc.

**Comment by jmcdo29** [comment] 2022-10-09 09:03
You can add 
```ts
console.log(`Application running at ${await app.getUrl()}`)
```
after `await app.listen(3000)` to get the URL it's running at. 

This has been discussed in the past as well, by the way

**Comment by micalevisk** [comment] 2022-10-09 15:24
duplicate of #8869 and #3306

**Closed by micalevisk** 2022-10-09 15:24 UTC
Labels: type: duplicate :wastebasket:, type: enhancement :wolf:, needs triage

**Comment by awaisarif18** [comment] 2023-11-22 11:21
> You can add
> 
> ```ts
> console.log(`Application running at ${await app.getUrl()}`)
> ```
> 
> after `await app.listen(3000)` to get the URL it's running at.
> 
> This has been discussed in the past as well, by the way

Where can I console log it in the application?

**Comment by MetythornPenn** [comment] 2024-02-02 07:13
add this part : 
`console.log(`Application is running on: ${await app.getUrl()}`);`
after `await app.listen(3000);`

**Comment by basememara** [comment] 2024-03-01 17:56
This prints `http://[::1]:3000` as the app URL 😕

**Comment by thooams** [comment] 2025-02-18 10:59
Hi, I think that the framework should manage these information, not the developer via a console.log. Look at the Rails side. There’s puma, when I start the server via `rails s`:
I’ve :
- the server name with this version
- the ruby version
- the number of threads
- the adress and port

Btw: Impossible to add a console.log via a container.

![Image](https://github.com/user-attachments/assets/948dd70f-55a3-4f83-abca-c2bc057f5c03)
