### ISSUE TITLE
integration (nestjs + svelte) not detect svelte changes

### ISSUE THREAD

**Issue by solinad21** [nestjs/nest#7388] opened 2021-07-04 22:32 UTC
i am using svelte files and run ok, but nestjs not detect svelte file changes.

are there some settings (tsconfig.json, etc) that can help me to detect svelte file changes????

https://github.com/munxar/nest-svelte

**Comment by jmcdo29** [comment] 2021-07-04 23:55
Looks like a duplicate of nestjs/nest-cli#1136

**Closed** 2021-07-05 07:09 UTC
Labels: needs triage, type: question 🙌
