### ISSUE TITLE
Returnining null as JSON Response doesn't work

### ISSUE THREAD

**Issue by ericmorand** [nestjs/nest#10415] opened 2022-10-18 19:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When returning `null` in a controller, alongside a `application/json` content type, the response is empty instead of containing the `null` value serialized as JSON.

### Minimum reproduction code

https://github.com/ericmorand/nestjs-null

### Steps to reproduce

* npm install
* ts-node src/index.ts

Then execute a GET request to `localhost:3000/null`.

### Expected behavior

The raw response consists of the `null` value serialized to JSON - namely the string "null".

For reference, the following code return the string "null":

```js
JSON.stringify(null);
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.1.4

### Node.js version

16.17.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment] 2022-10-18 21:01
There's [a specific check against a `nil` (null or undefined) body](https://github.com/nestjs/nest/blob/master/packages/platform-express/adapters/express-adapter.ts#L60) in place. What's the use case you have to send back null? If you need you can `return 'null'` or `return JSON.stringify(null)` to get around the `res.send()`

**Comment by ericmorand** [comment] 2022-10-19 18:55
Let's let the use case aside for a minute: `null` is a perfectly valid value in JSON. Returning the string "null" is not the same as returning `null`.

```json
null
```

```json
"null"
```

Are different things: the first one is the `null` value, the second one is the string "null".

Now about the use case: a resource can totally be `null`. We have a system that returns either something or `null` for a given id. In ou case `null` means something that is different from "the resource doesn't exist" which would return a 404 response. Here `GET /resource/5` for example would return a 200 response with `null` because resource 5 is `null`. This is different that `GET /resource/doesnotexist` that would return a 404 response.

What is the use case that you handle by checking against a `nil` body? Are there specification somewhere that establishes that `null` is not a valid response body?

**Comment by micalevisk** [comment] 2022-10-19 19:23
that line was written 4 years ago... Could you please test that using the fastify adapter instead?

I believe we should use `isUndefined(body)` instead in there, then it will end up calling ` response.send(String(body))`

**Comment by jmcdo29** [comment] 2022-10-19 20:55
By the way, it looks like even if we only check for `undefined` [express will still set `null` to `''` like we do](https://github.com/expressjs/express/blob/master/lib/response.js#L155). Fastify seems to send `null` back, but I'm not sure how that gets encoded and transferred over HTTP

**Comment by ericmorand** [comment] 2022-10-22 09:12
So maybe the issue is on express side. It is strange that they implemented a specific handling for `null` instead of relying on their default case `return this.json(chunk);` that would have returned the expected `null` JSON.

**Comment by kamilmysliwiec** [comment] 2022-10-24 10:54
> What do you think? Should I open an issue there and close this one?

Sounds good!

**Closed by kamilmysliwiec** 2022-10-24 10:54 UTC
Labels: needs triage

**Comment by OSA413** [comment] 2023-09-12 10:07
I guess the issue is still here. @ericmorand was the issue created (or found a related one) for express?

**Comment by OSA413** [comment] 2023-09-12 10:20
Btw in case if you want to send an "empty" object, you should probably throw 404 error or send a placeholder object with null properties.

**Comment by ericmorand** [comment] 2023-09-12 13:02
@OSA413 I did not create an issue, I switched framework to neither use express nor Nest.

About that:

> Btw in case if you want to send an "empty" object, you should probably throw 404 error or send a placeholder object with null properties.

There is a difference between an empty object and a non existing object. An empty object exists. It should be returned alongside a 200 HTTP response. 404 is about a missing resource. Which an empty object is not.
