### ISSUE TITLE
spawn pgrep EAGAIN Error reported after modifying the listening file

### ISSUE THREAD

**Issue by Nexta1** [nestjs/nest#12573] opened 2023-10-16 17:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I will get this error message after updating the file
Error: spawn pgrep EAGAIN
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -35,
  code: 'EAGAIN',
  syscall: 'spawn pgrep',
  path: 'pgrep',
  spawnargs: [ '-P', 21160 ]
}

### Minimum reproduction code

  "start:dev": "nest start --watch"

### Steps to reproduce

1. npm run start:dev
2. Modify the code and save it
3. And then the error appears

### Expected behavior

Normal execution

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### NestJS version

10

### Packages versions

```json
 "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
```

### Node.js version

16.17.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

I don't know, but there were no other errors in my search

**Comment by Nexta1** [comment] 2023-10-16 18:12
[02:08:58] File change detected. Starting incremental compilation...

[02:08:58] Found 0 errors. Watching for file changes.

node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: spawn pgrep EAGAIN
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -35,
  code: 'EAGAIN',
  syscall: 'spawn pgrep',
  path: 'pgrep',
  spawnargs: [ '-P', 66834 ]
}

Node.js v20.5.1

This is my newly created project, but after updating the file, an error will be reported. My system is Mac OS14

**Comment by micalevisk** [comment] 2023-10-16 23:18
I didn't manage to reproduce this on Linux with nodejs v20.8.1 :/ I don't have a MacOS

**Comment by Tony133** [comment] 2023-10-17 19:43
I use MacOS but I couldn't reproduction it, I used node v20.5.1, node v20.8.1, but nothing, it works for me.

@Nexta1 have you tried reinstalling Node?

**Comment by micalevisk** [comment] 2023-10-17 19:48
thanks tony

I'll close this as this doesn't seems to be something that we could fix on the fw side. Perharps you have a missing nodejs dependency(?)

@Nexta1 if you find a working version of `@nestjs/cli`, I can check this out again.

**Closed by micalevisk** 2023-10-17 19:48 UTC
Labels: needs triage
