### ISSUE TITLE
Allow injection of an array of providers

### ISSUE THREAD

**Issue by maphe** [nestjs/nest#4786] opened 2020-05-12 18:16 UTC
## Is your feature request related to a problem? Please describe.

Eg. given the following service:
```typescript
@Injectable()
export class MyService {
  constructor(
    private readonly gatherers: Gatherer[],
    private readonly notifiers: Notifier[]) {
  }

  //... do stuff
}
```
There's no way to handle a clean dependency injection.

## Describe the solution you'd like

I'd like to be able to have two lists of providers I can inject in the module setup.

#### Option 1: Factory
```typescript
  providers: [
    Gatherer1,
    Gatherer2,
    Notifier1,
    Notifier2,
    Notifier3,
    {
      provide: MyService,
      useFactory: (gatherers: Gatherer[], notifiers: Notifier[]) => {
        return new MyService(gatherers, notifiers)
      },
      inject: [
        [Gatherer1, Gatherer2],
        [Notifier1, Notifier2, Notifier3]
      ]
    }
  ]
```

#### Option 2: Provider as an array of providers
```typescript
@Injectable()
export class MyService {
  constructor(
    @Inject(GATHERER_LIST) private readonly gatherers: Gatherer[],
    @Inject(NOTIFIER_LIST) private readonly notifiers: Notifier[]) {
  }

  //... do stuff
}
```

```typescript
  providers: [
    Gatherer1,
    Gatherer2,
    Notifier1,
    Notifier2,
    Notifier3,
    {
      provide: GATHERER_LIST,
      useProviders: [Gatherer1, Gatherer2] // maybe the existing useClass here
    },
    {
      provide: NOTIFIER_LIST,
      useProviders: [Notifier1, Notifier2, Notifier3]
    }
  ]
```

## What is the motivation / use case for changing the behavior?
I ended up using the following workaround for now, but this is not ideal nor super flexible, and very custom made:
```typescript
  providers: [
    Gatherer1,
    Gatherer2,
    Notifier1,
    Notifier2,
    Notifier3,
    {
      provide: MyService,
      useFactory: (...params: (Gatherer|Notifier)[]) => {
        const gatherers = [];
        const notifiers = [];
        for (const injection of params) {
          if (injection instanceof AbstractGatherer) gatherers.push(injection);
          if (injection instanceof AbstractNotifier) notifiers.push(injection);
        }
        return new MyService(gatherers, notifiers)
      },
      inject: [Gatherer1, Gatherer2, Notifier1, Notifier2, Notifier3]
      ]
    }
  ]
```

**Comment by tonivj5** [comment] 2020-05-12 20:10
I think this is dupe of https://github.com/nestjs/nest/issues/770

**Comment by maphe** [comment] 2020-05-12 20:45
Yes, kind of. It seems to address the same use case, but the implementation proposal is different (simpler here, imo).

**Comment by kamilmysliwiec** [comment] 2020-05-13 06:50
```
{
   provide: GATHERER_LIST,
   useProviders: [Gatherer1, Gatherer2] // maybe the existing useClass here
},
```

Maybe instead of introducing a new property, we could use the existing one named `useExisting` and detect if the specified value == array. If so, construct a "multi" provider.

I think this approach is cleaner & more explicit then having the `multi` property as Angular (which is not that simple in Nest due to per-module providers scoping). cc @BrunnerLivio What do you think?

**Comment by BrunnerLivio** [comment] 2020-07-23 12:12
@kamilmysliwiec sorry missed that issue. In fact, my PR #2460 uses a very similar construct as you have described in the comment above. Though it "generates" this "collection" provider automatically.

When adding a multi-provider from #2460 , it will add the following providers:

```typescript
{
  provide: GATHER_LIST,
  useValue: Gatherer1,
  multi: true,
}
```

and it will internally create this "collection" provider which collects all the providers with the same token automatically

```typescript
{
  provide: GATHER_LIST
  useValue: [Gatherer1, ...],
  inject: [Gatherer1, ...],
}
```

so when the user adds another `GATHER_LIST` provider, it will add it to the collection provider.

---

So to come to a conclusion, I think the solution you've provided is good for a workaround, but `multi` provider are simpler to use for the user, because he/she does not need to worry about this collection provider.

**Comment by lukaszwilisowski** [comment] 2020-10-07 19:51
Hi. Let me add some points into the discussion:

1. @maphe is right that injection of array of providers is useful in services (see inversify's multi injection)
2. The prerequisite for this is that underlying DI container must allow for registering more than 1 provider for a given symbol. 
3. DI container must implement a getAll() function, returning an array of providers for a given symbol.  
4. As for registration: these two use cases should be handled:
- for a given symbol, register an array of providers
- for a given symbol, add a new provider to existing array of providers

The second case is particularly useful in plugin-module architecture that is based on SOLID principles. 

For example: with each module I want to register a new implementation of my IExtension interface. This would allow me to read at runtime an array of registered IExtensions without knowing the details of all the modules (pure SOLID).  

Current workaround that I know of: use cache service to cache instances of singleton providers. I believe it gets more difficult with request-scoped providers. 

Another example: I would like to create an old, good SOLID decorator for an interface. 
Example: classes XA and XY implement interface X. Class XA extends (decorates) functionality of class XY by injecting XY (decoratee) as constructor parameter. 

`export class FoobarNotificationDecorator implements IFoobarService {
  constructor(
    private readonly decoratee: IFoobarService,
    private readonly notificationService: IFolderService,
  ) {}

  getFooBarById(id: number): Promise<IFoobar | undefined> {
    this.notificationService.doSth();
    return this.decoratee.getFooBarById(id);
  }`

Currently this is impossible in nestjs and I belive it could be a start of another discussion. But with multi-injection possible I would be able to easily create a factory that creates a provider and applies all decorators (that are registered for a symbol such as 'ServiceDecorator'), allowing for a nice modular architecture.

**Comment by lukaszwilisowski** [comment] 2020-10-08 17:05
For anyone interested in the possible solutions: 

This website: https://dev.to/nestjs/advanced-nestjs-dynamic-providers-1ee got me thinking. 

**1. In order to register multiple providers for one symbol:**

Yu can use the same method as in the webiste above: basically storing an array of providers in a global variable. 
This solution is not really reusable across different programming languages and it uses the fact that every exported global variable in node.js is a singleton. So all in all this should be considered as a workaround, not a good SOLID pattern. 

**2. In order to create an old-type interface decorator**

Let's imaging web application as an operating system to which you can install any patches. 
The goal is to be able to add / change / remove ANY functionality in the system without changing the source code of original module. Generally, we can extend existing modules in 4 different ways by: 
- reusing existing providers (composition by constructor injection)
- replacing existing providers (not really doable in nest.js outside unit tests) - workaround required 
- listening to event, observables, etc (nice pattern but it leaks a little abstraction, meaning that it requires that original code is an observable or emits events that can be listened to)
- decorating existing functionalities with SOLID decorator pattern https://en.wikipedia.org/wiki/Decorator_pattern
This last one method is rarely used in back-end architectures although it is probably the best method to extend existing functionality. It leask zero (0!) abstraction because it does not impose any requirements on the orignal code. 

To achieve sth similar in nest.js you can do:

1. Create a typescript decorator such as this

```typescript
/* eslint-disable @typescript-eslint/ban-types */
export const decoratedClasses: Record<string, Function[]> = {};

/** 
 * Marks this class as decorating another provider.
 */
export const Decorates = (
  decoratedProvider: symbol, 
): ClassDecorator => 
  <T extends Function>(target: T) => {
    const stringKey = decoratedProvider.toString();

    if (decoratedClasses[stringKey] === undefined) 
      decoratedClasses[stringKey] = [target];
    else 
      decoratedClasses[stringKey] = [...decoratedClasses[stringKey], target];
  };
```

2. Create decorator provider interface
```typescript
export interface IDecoratorProvider<T> {
  provideDecoratorFor(decoratee: T): T;
}
```

This layer is necessary to automatically inject any dependency of factory decorator.

3. Create example provider and its decorator: you can decorate providers as well as factories of providers as in this example:
Provider (factory): MongoDbRepositoryFactory
Decorator: CachedMongoDbRepositoryFactoryDecorator (adds cache to repository created by the factory, not shown here as implementation is not important for this example)
Decorator Provider: CachedMongoDbRepositoryFactoryDecoratorProvider 

```typescript
@Injectable()
@Decorates(MongoDbTypes.MongoDbRepositoryFactory)
export class CachedMongoDbRepositoryFactoryDecoratorProvider
implements IDecoratorProvider<IRepositoryFactory> {

  public constructor (
    @Inject(CachingTypes.CachingService)
    private readonly cachingService: CachingService,
  ) {}

  public provideDecoratorFor(decoratee: IRepositoryFactory<T, A, E>): IRepositoryFactory<T, A, E> {
    return new CachedMongoDbRepositoryFactoryDecorator(decoratee, this.cachingService);
  }
}
```

4. Create an extension module which registers decorator as a provider. The module must be global for decorator to be applied dynamically to previously registered provider. 

```typescript
/** 
 * * This module is marked as global because it exports at least one decorator which should be applied dynamically, 
 * * without original module knowing about it.  
 */
@Global() 
@Module({
  imports: [
    CachingModule, 
  ],
  controllers: [],
  providers: [CachedMongoDbRepositoryFactoryDecoratorProvider],
  exports: [CachedMongoDbRepositoryFactoryDecoratorProvider]
})
export class MongoDbCachedModule {}
```

5. Create helper to register providers that can be dynamically extended by decorators from other modules
```typescript
export const createDecoratedProvider = <T>(name: symbol, baseProviderClass: new(...args: never[]) => T
): Provider<T> => ({
  provide: name,
  useFactory: <T>(
    baseProviderClass: T, 
    ...decorators: IDecoratorProvider<T>[]
  ) => {
    if (decorators.length === 0) 
      return baseProviderClass;
    
    let decoratedInstance = baseProviderClass;
    for (const decorator of decorators) {
      decoratedInstance = decorator.provideDecoratorFor(decoratedInstance);
    }

    return decoratedInstance;
  },
  inject: [baseProviderClass, ...decoratedClasses[name.toString()]],
  scope: Scope.REQUEST
});
```

Example usage: 
```typescript
@Module({
  imports: [...],
  controllers: [],
  providers: [ 
  MongoDbRepositoryFactory,
  createDecoratedProvider(
    MongoDbTypes.MongoDbRepositoryFactory, 
    MongoDbRepositoryFactory
  )],
  exports: [MongoDbTypes.MongoDbRepositoryFactory]
})
export class MongoDbModule {}
```

It works in my case and allows to register any number or extensions to original service (provider) without original service knowing about it. 

If anyone finds a simpler workaround to enable this feature please let me know. Hope that helps anyone.

**Comment by RezaRahmati** [comment] 2021-01-06 02:17
I found the below working

```ts
export interface ITask {
  start(): void;
}

@Injectable()
export class EmailTask implements ITask {
  start(): string {
    return 'start sending email';
  }
}

@Injectable()
export class SmsTask implements ITask {
  start(): string {
    return 'start sending sms';
  }
}
```
then in my module

```
providers: [
    EmailTask ,
    SmsTask ,
    {
      provide: 'Tasks',
      useFactory: (email, sms) => [email, sms],
      inject: [EmailTask , SmsTask ],
    },
  ],
```
and then in the service or controller
```
constructor(@Inject('Tasks') private tasks: Array<ITask>) {
  }

async foo() {
  return this.tasks.map(task => task.start());
}
```

**Comment by kamilmysliwiec** [comment] 2021-01-27 10:37
You can register a provider that groups multiple other providers and forms an array, as @RezaRahmati has shown above https://github.com/nestjs/nest/issues/4786#issuecomment-755032258. If you are looking for a more "automated" solution, we're tracking another feature that should allow registering such implicit "array-based" providers here https://github.com/nestjs/nest/issues/770

**Closed by kamilmysliwiec** 2021-01-27 10:37 UTC
Labels: scope: core, type: enhancement :wolf:
