### ISSUE TITLE
Microservices - ClientProxy

### ISSUE THREAD

**Issue by Sikora00** [nestjs/nest#2728] opened 2019-08-09 10:30 UTC
## Current behavior
Code from the documentation doesn't send a request to microservices
```ts
accumulate(): Observable<number> {
  const pattern = { cmd: 'sum' };
  const payload = [1, 2, 3];
  return this.client.send<number>(pattern, payload);
} 
```
Events also don't work
```ts
 return this.client.emit(event, payload);
```
## Expected behavior
The code above should send requests to microservices as it is described in the documentation

## Possible Solution
It is necessary to subscribe to returned values from that methods 
```ts
this.client.send<number>(pattern, payload).subscribe().
```
After that the request is sent.
Observable used in the ClientProxy should be a hot one not a cold
 
## Environment

<pre><code>
- Platform:  Linux
- @nestjs/core: 6.5.2,
- @nestjs/microservices: 6.5.3,
- ts-node: 8.3.0

**Comment by kamilmysliwiec** [comment] 2019-08-13 08:15
Duplicate of https://github.com/nestjs/nest/issues/2718

**Closed by kamilmysliwiec** 2019-08-13 08:15 UTC
Labels: needs triage
