### ISSUE TITLE
EventHandler pattern fails to subscribe to Redis channel

### ISSUE THREAD

**Issue by RoxKilly** [nestjs/nest#7406] opened 2021-07-06 01:35 UTC
## Current behavior
- I successfully connect to Redis using `client.connect()`
- I successfully emit an event using `client.emit()`
- My controller handler decorated with `@EventPattern` does not get triggered

## Input Code
[Source code](https://send.bitwarden.com/#80wtWmbUHES9qK1dAA7WNQ/0Ofmar46Ga4O2LXhuHHMjg) can be downloaded and run

### main.ts
```ts
async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  await NestFactory.createMicroservice<RedisOptions>(AppModule, {
    transport: Transport.REDIS,
    options: { url: 'redis://localhost:6379' },
  });
  await app.listen(3000);
}
bootstrap();
```

### AppModule
```ts
@Module({
  imports: [TransportModule],
  controllers: [AppController],
})
export class AppModule {}
```

### AppController handler
```ts
  @EventPattern(EVENT_NAME) // <- EVENT_NAME is string constant 'EVENT_NAME'
  onEvent(data: any) {
    Logger.log('Event received'); // <- this is never executed
    Logger.log(data);
  }
```

### TransportModule
```ts
export const EVENT_NAME = 'EVENT_NAME';
export const NEST_REDIS = Symbol('NEST_REDIS');

export const RedisProvider: Provider = {
  provide: NEST_REDIS,
  useFactory: () =>
    ClientProxyFactory.create({
      transport: Transport.REDIS,
      options: { url: 'redis://localhost:6379' },
    }),
};

@Module({ providers: [RedisProvider] })
export class TransportModule implements OnApplicationBootstrap {
  constructor(@Inject(NEST_REDIS) private client: ClientRedis) {}

  onApplicationBootstrap() {
    this.client.connect().then(() => {
      Logger.log('REDIS is connected');
      this.startEmitting();
    });
  }

  startEmitting() {
    let msgNumber = 0;

    // wait 3 secs, then start emitting every 8
    timer(3000, 8000)
      .pipe(
        tap(() => Logger.log(`Emitting message #${++msgNumber}`)),
        tap(() => this.client.emit(EVENT_NAME, { messageNumber: msgNumber })),
      )
      .subscribe();
  }
}
```

### Application Log
![Screenshot 2021-07-05 204414](https://user-images.githubusercontent.com/12346501/124528925-6bba2300-ddd7-11eb-9007-ceba15ef2fe4.png)

### redis-cli log
![Screenshot 2021-07-05 210505](https://user-images.githubusercontent.com/12346501/124528955-7d9bc600-ddd7-11eb-9bcb-4fe296d80399.png)

In the redis-cli log above, the 3rd line of response to my subscribe call is `(integer) 1`;  this leads me to believe that NestJS is not subscribed to this channel at all (that the redis-cli is the 1 subscriber)

### redis-server log
When the application starts up, the `redis-server` log shows two accepted connections on consecutive ports (I assume that's when I make the `client.connect()` call)

## Expected behavior
I expected that when I use `client.emit(EVENT_NAME)`,  the controller handler decorated with `@EventPattern(EVENT_NAME)` would be executed with the event payload

## Environment
<pre><code>
Nest version: 7.6.18
Redis 6.2.4
redis (NPM library) 3.1.2

 
For Tooling issues:
- Node version: 16.4.0 
- Platform:  Windows 10, but Redis is installed and running from the Windows subsystem for Linux
 
Other:
No error logged anywhere that I can find

</code></pre>

Sorry for the long post.  In case you missed it, the [source files are available here](https://send.bitwarden.com/#80wtWmbUHES9qK1dAA7WNQ/0Ofmar46Ga4O2LXhuHHMjg).

**Comment by RoxKilly** [comment] 2021-07-06 02:00
also [posted on StackOverflow](https://stackoverflow.com/questions/68263350/nestjs-clientredis-emits-but-eventpattern-handler-not-triggered) in case this is user error and not a bug

**Comment by RoxKilly** [comment] 2021-07-06 03:50
Interestingly, if I try to take over the protected `subClient` within the `ClientRedis` instance of NestJS, I can subscribe to and receive those messages.  Consider this code, which I tried to run at the top of `TransportModule.startEmitting` from earlier:
```ts
  listen() {
    this.client['subClient'].subscribe(EVENT_NAME);
    this.client['subClient'].on('message', (channel, message) => {
      console.log(`subClient received; channel=${channel}, message=${message}`);
    });
  }
```

With this running, the controller handler still does not get triggered, but I can now see the messages come through in the logs:

![Screenshot 2021-07-05 234959](https://user-images.githubusercontent.com/12346501/124539578-c1002f80-ddeb-11eb-8899-3c03c2af1204.png)

**Comment by kamilmysliwiec** [comment] 2021-07-06 06:49
Please, provide a minimum reproduction repository **on Github**.

**Comment by RoxKilly** [comment] 2021-07-06 07:09
@kamilmysliwiec  Sure.  Here it is: https://github.com/RoxKilly/nestjs-redis-troubleshoot

**Comment by kamilmysliwiec** [comment] 2021-07-06 07:28
Your minimum reproduction repository is invalid. In the `main.ts` file, you create the microservice instance:

```typescript
await NestFactory.createMicroservice<RedisOptions>(AppModule, {
  transport: Transport.REDIS,
  options: { url: 'redis://localhost:6379' },
});
```
but since it's not assigned to any variable, it's automatically garbage collected (and the `Redis` "consumer" does not even bootstrap).

After making the following changes:

![image](https://user-images.githubusercontent.com/23244943/124559900-7d81e180-de3c-11eb-9dfa-990ae7bb717f.png)

everything will start working as expected:

![image](https://user-images.githubusercontent.com/23244943/124559923-85418600-de3c-11eb-8c20-5d767dfcf568.png)

**Closed by kamilmysliwiec** 2021-07-06 07:28 UTC
Labels: needs clarification

**Comment by RoxKilly** [comment] 2021-07-06 08:20
Thank you @kamilmysliwiec  I suspected as much.  May I suggest that at least one of the examples on the [Microservices section](https://docs.nestjs.com/microservices/basics) of the docs shows or links to this `logAsync` usage ?  I read through that page, and also the Redis page several times over in the last 12hrs but the answer isn't there.

I appreciate your time, and I'm a big fan of your project.

**Comment by RoxKilly** [comment] 2021-07-07 05:30
Hello.  The solution offered above creates two full instances of the application (I have 2 AppModules and everything else).  This led to some hard to debug errors.

In Kamil's solution, I changed this line::

```ts

const microservice =  await NestFactory.createMicroservice<RedisOptions>(AppModule, {
    transport: Transport.REDIS,
    options: { url: 'redis://localhost:6379' },
  });
```

To this:

```ts
const microservice = app.connectMicroservice({
    transport: Transport.REDIS,
    options: { url: 'redis://localhost:6379' },
  });
```

**Comment by RoxKilly** [comment] 2021-07-07 05:33
The relevant section of the documentation:
https://docs.nestjs.com/faq/hybrid-application#hybrid-application

**Comment by kamilmysliwiec** [comment] 2021-07-07 06:33
Yep, that was just an example. Using hybrid apps approach is totally fine
