### ISSUE TITLE
graphql introspectComments doesn't seem to work

### ISSUE THREAD

**Issue by Rjrunner44** [nestjs/nest#6404] opened 2021-02-13 15:33 UTC
## Bug Report

adding this to nest-cli.json doesn't introspect comments out to schema.gql:

```
{
                "name": "@nestjs/graphql",
                "options": {
                    "introspectComments": true,
                    "typeFileNameSuffix": [
                        ".dto.ts",
                        ".model.ts",
                        ".args.ts",
                        ".entity.ts",
                        ".interface.ts"
                    ]
                }
            }
```

example dto type:

```
@ObjectType()
export class BookInstance {
  /**
   * The instance name.
   * @example 'library_4'
   */
  @Field()
  @IsNotEmpty()
  name!: string;
...
```

unless I specifically add {description: 'xxxxxxx"} to the @Field() decorator there are no comments added to graphql doc.:

```
@ObjectType()
export class BookInstance {
  /**
   * The instance name.
   * @example 'library_4'
   */
  @Field({
    description:
      `The instance name. @example 'library_4'`,
  })
  @IsNotEmpty()
  name!: string;
...
```

thanks.

**Comment by Tony133** [comment] 2021-02-13 15:54
Hi @Rjrunner44, I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported.

However if you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

**Comment by Rjrunner44** [comment] 2021-02-13 15:57
don't have time to do that right now, sorry...close it if you want...

**Comment by Rjrunner44** [comment] 2021-02-13 15:59
further, if you have @Exclude on the field it DOES introspect the comment 🤣

  /**
   * zzzThe name of the data table for this asset, typically a munged form of the asset EWNS
   * @example 'msg_hydro1_market_adivate_ewc'
   */
  @Exclude()
  @IsNotEmpty()
  msgTableName!: string;

**Comment by Rjrunner44** [comment] 2021-02-13 16:02
ok, has anyone ever even used this?

this introspects comments into gql:

  /**
   * The EW-Switchboard role which DER DIDs much possess in order to send messages to this asset.
   * @example 'datapub.roles.market1.apps.adivate.iam.ewc'
   */
  @IsNotEmpty()
  dataPublishRole!: string;

this does not:

  /**
   * The EW-Switchboard role which DER DIDs much possess in order to send messages to this asset.
   * @example 'datapub.roles.market1.apps.adivate.iam.ewc'
   */
  @Field()
  @IsNotEmpty()
  dataPublishRole!: string;

and further, if you have @Exclude and are using the graphql-cli plugin, it ignores that and puts the field right back into your schema:

  /**
   * zzzThe name of the data table for this asset, typically a munged form of the asset EWNS
   * @example 'msg_hydro1_market_adivate_ewc'
   */
  @Exclude()
  @IsNotEmpty()
  msgTableName!: string; <---- this appears in GQL schema even with @Exclude on it

**Comment by Rjrunner44** [comment] 2021-02-13 16:25
one more, if you have to use @field to annotate the type, you must hard-code the description anyway also:

e.g.

  /**
   * The number of unique addresses which have created assets
   * @example 4
   */
  @Field((type) => Int)
  @IsNotEmpty()
  addresses!: number;
  
  introspectComments and that are incompatible.

**Comment by Rjrunner44** [comment] 2021-02-13 16:46
I'll try to make a clean test repo for all these when I can...

**Comment by jmcdo29** [comment] 2021-02-13 18:10
So, with this `nest-cli.json`
```json
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "plugins": [
      {
        "name": "@nestjs/graphql",
        "options": {
          "typeFileNameSuffix": [".input.ts", ".args.ts", ".model.ts"],
          "introspectComments": true
        }
      }
    ]
  }
}
```
And with this model
```ts
// foo.model.ts
import { ObjectType } from '@nestjs/graphql';

@ObjectType()
export class Foo {
  /**
   * This property has comments. Yay! :tada:
   */
  bar: string;
}
```
I got back this schema file
```gql
# ------------------------------------------------------
# THIS FILE WAS AUTOMATICALLY GENERATED (DO NOT MODIFY)
# ------------------------------------------------------

type Foo {
  """This property has comments. Yay! :tada:"""
  bar: String!
}

type Query {
  sayHello: Foo!
}
```
and in the playground I see this:
![Screenshot from 2021-02-13 10-09-00](https://user-images.githubusercontent.com/28268680/107857506-8ddce580-6de3-11eb-8a16-d6228dea5e28.png)
So I can't reproduce the problem you're facing. If you can provide a minimum reproduction, we will take another look. Closing the issue for now.

**Closed by jmcdo29** 2021-02-13 18:10 UTC
Labels: needs triage

**Comment by Rjrunner44** [comment] 2021-02-13 19:33
you proved the simplest possible case works, while what i actually reported was ignored. which are the two cases users will certainly encounter.

**Comment by jmcdo29** [comment] 2021-02-13 19:37
I provided a __minimum reproduction__ to show that the functionality that the docs say _should_  work, actually does. If you have a problem, provide us with the same. A [minimum reporduction](http://minimum-repdocution.wtf) that can be cloned, installed, and ran to see the issue. I'll convert mine to a git as well if you'd like to be able to play with it.

**Comment by Rjrunner44** [comment] 2021-02-13 19:43
bro you already have the repo setup lolol just add one field with an explicit type, another one with nullable set and another one with exclude decorator. then see what happens 🤣🤣

**Comment by jmcdo29** [comment] 2021-02-13 19:47
If you spent a day on this you would've have had the time to create a minimum reproduction. It takes 10 minutes max. I'll give it a shot here soon, after I finish what I'm currently working on. Next time you want to report a bug, instead of providing snippets and screenshots, provide a git reproduction.

**Comment by Rjrunner44** [comment] 2021-02-13 19:59
yup didn’t have time and am away from computer now also. just trying to help 

basically you can’t use the cli if you have any @field or @exclude decorators anywhere in your code

**Comment by kamilmysliwiec** [comment] 2021-02-15 08:48
As @jmcdo29  mentioned, next time you want to report a "bug", provide a git reproduction.

**Comment by jmcdo29** [comment] 2021-02-15 16:29
I was able to notice that if a type is explicitly set using `@Field(() => Type)` then the comments don't appear. There's only a few cases where that would need to be done, but it is probably something we should look into. I'll open a reproduction on the GraphQL repo if you want.

As for `@Exclude()`, that's a `class-transformer` decorator, and there's nothing in the docs that say that Nest will support those via the CLI plugin. If you want a nullable property you can use the `?` property modifier, and if you want a property to not be on the schema at all you can use  `@HideField()` [as the docs mention](https://docs.nestjs.com/graphql/cli-plugin#overview)
