### ISSUE TITLE
[BUG] Relative import

### ISSUE THREAD

**Issue by gquittet** [nestjs/nest#1025] opened 2018-08-31 11:56 UTC
Why Nest.JS doesn't support relative import?
When I run `yarn dev`, `nodaemon` find easily all the dependencies with the relative import.
But, when I run `yarn build` and `node dist/main.js`, I've got this error:
```
Error: Cannot find module '..........'
```

I want to import with:
```typescript
import { test } from 'tools/test';
```

and not with:
```typescript
import { test } from '../../../../../tools/test';
```

Here's my tsconfig.json file:
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": false,
    "noImplicitAny": false,
    "removeComments": true,
    "noLib": false,
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es6",
    "sourceMap": true,
    "allowJs": true,
    "outDir": "dist",
    "baseUrl": "src",
    "paths": {
         "tools/*": [ "tools/*" ]
    }
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts"
  ]
}
```

**Comment by kamilmysliwiec** [comment] 2018-08-31 12:11
This issue isn't related to Nest. Duplicate of #986

**Closed by kamilmysliwiec** 2018-08-31 12:11 UTC

**Comment by gquittet** [comment] 2018-08-31 12:38
It's working! Thank you very much! 👍 

I've just created a file at the root of the project with this name: `tsconfig-paths-bootstrap.js`
I put this content into it:
```javascript
const tsConfig = require('./tsconfig.json');
const tsConfigPaths = require('tsconfig-paths');

const baseUrl = './dist'; // Either absolute or relative path. If relative it's resolved to current working directory.
tsConfigPaths.register({
  baseUrl,
  paths: tsConfig.compilerOptions.paths,
});
```

Then, I've edited the `start:prod` script from package.json to look like this:
```json
"start:prod": "node -r ./tsconfig-paths-bootstrap.js dist/main.js",
```

**Comment by kamilmysliwiec** [comment] 2018-08-31 12:42
🔥
