### ISSUE TITLE
Redis microservice does not start

### ISSUE THREAD

**Issue by davidpodhola** [nestjs/nest#8710] opened 2021-11-26 05:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you follow the steps in https://docs.nestjs.com/microservices/basics and https://docs.nestjs.com/microservices/redis, your microservice will not start but will end immediately. Note this is not happening with the TCP transport. Also it looks like it does not matter if the Redis server is actually started or not.

![image](https://user-images.githubusercontent.com/436605/143533365-48457517-a8f5-4b2c-b05d-0ff1ebc37b0c.png)

### Minimum reproduction code

https://github.com/davidpodhola/nestjs-redis-microservice-problem

### Steps to reproduce

1. `npx @nestjs/cli new redis-microservice`
2. `cd redis-microservice`
3. `npm i --save @nestjs/microservices`
4. `npm i --save redis`
5. open the `src\main.ts` file and replace the lines for `const app=` with the lines from https://docs.nestjs.com/microservices/redis#overview
6. `npm start`

### Expected behavior

The microservice application will start and listen for the requests the same way it works if you use the TCP transport.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

redis

### NestJS version

8.2.3

### Packages versions

{
  "name": "redis-microservice",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/microservices": "^8.2.3",
    "@nestjs/platform-express": "^8.0.0",
    "redis": "^4.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "27.0.2",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "^27.2.5",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

### Node.js version

14.18.1 on Windows, 12.22.5 on macOS

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [ ] Linux

### Other

Found this as a part of the investigation why trying to migrate to hybrid applications does not work.

**Comment by codematters-pl** [comment] 2021-11-26 15:32
I have exactly the same problem. I'm trying to create hybrid app. When I tried to use TCP transport, it worked well. This is something related to Redis I guess. I tried also to downgrade version of redis package to 3.1.2, but it didn't help.

**Comment by jmcdo29** [comment] 2021-11-26 16:09
I had luck reverting the minimum reproduction down to `redis^3` (3.1.2 is what it resolved to). Looks like redis v4 released some breaking changes about a week ago that we'll need to try and address soon

**Comment by davidpodhola** [comment] 2021-11-26 16:10
@codematters-pl looks to be the same. I have switched to MQMT for the time being to be able to go on, but we need Redis as it is already in place.

**Comment by codematters-pl** [comment] 2021-11-26 16:12
I did a downgrade of @nestjs/core (and some other packages) to 8.2.2 and Redis works well. When I kept other packages on version 8.2.2 and upgraded just @nestjs/core to 8.2.3, then I was able to reproduce the problem.

**Comment by jmcdo29** [comment] 2021-11-26 16:15
Common and core should be on the same version at all times, just an FYI

**Comment by codematters-pl** [comment] 2021-11-26 16:18
Aaaa, I forgot that. Even if I upgraded these two packages to 8.2.3, microservice is not starting.

**Comment by jmcdo29** [comment] 2021-11-26 16:19
Everything (common, core, microservices, and platform-express) are all on 8.2.3 for me and it's working fine.

**Comment by davidpodhola** [comment] 2021-11-27 11:01
@jmcdo29 thanks, I can confirm downgrading Redis to `redis^3` solves my problem. Will open a PR to the documentation.

**Comment by kamilmysliwiec** [comment] 2022-07-07 07:32
This will be fixed in v9

**Closed by kamilmysliwiec** 2022-07-07 07:32 UTC
Labels: needs triage
