### ISSUE TITLE
NestJS deployement support

### ISSUE THREAD

**Issue by halimpuckjava** [nestjs/nest#2434] opened 2019-06-23 11:17 UTC
hi

i suggest to add support for deployment process of nestjs application

**Comment by BrunnerLivio** [comment] 2019-06-23 15:08
Duplicate of #591. 

From the issue:

**kamilmysliwiec**
> Exactly, I don't think that it's supposed to be a part of the framework documentation. However, I have a plan to write a set of articles. One of them will cover deployment stuff for sure, promise. 

**chriszrc**
> https://dev.to/antogarand/deploying-a-nestjs-application-on-aws-beanstalk-4no1

**Closed** 2019-06-23 15:08 UTC
Labels: needs triage, type: enhancement :wolf:

**Comment by halimpuckjava** [comment] 2019-06-30 10:33
so what the purpose of developing server without deploy it !!!!

Le dim. 23 juin 2019 à 17:09, Livio Brunner <notifications@github.com> a
écrit :

**Comment by appsolutegeek** [comment] 2019-06-30 10:37
@halimpuckjava There is nothing special about deploying the server. Its a standard node application.

There isn't any special nestjs training needed :-)

deploy it in docker, deploy it where ever.

Its a standard nodejs application.

Test it locally . (build it and then usually run "node main.js")
