### ISSUE TITLE
Add controllers dynamically

### ISSUE THREAD

**Issue by Disane87** [nestjs/nest#4373] opened 2020-03-21 14:37 UTC
Hey guys, is it possible to add controllers (with display in swagger) dynamically? I want to create asystem with headless CMS functionality where users can design their own tables and queries, but for this, I need the ability to create (virtual) controllers by document structure in my mondodb.

**Comment by izio38** [comment] 2020-03-21 16:37
Hi, please, next time wait a bit longer on Discord. I saw you asked this question, but Github should contains bugs or feature request only. https://docs.nestjs.com/modules#dynamic-modules.

Use the documentation search bar :)

**Comment by Disane87** [comment] 2020-03-21 17:28
Hey, sorry! I already studied the docs about this and I know how the dynamic modules work, but I need a way to create controllers at runtime (or in bootstrapping time)

**Comment by kamilmysliwiec** [comment] 2020-03-21 20:10
Duplicate of https://github.com/nestjs/nest/issues/1438

**Closed by kamilmysliwiec** 2020-03-21 20:10 UTC
