### ISSUE TITLE
Allow to specify `limit` for json parser

### ISSUE THREAD

**Issue by doublemcz** [nestjs/nest#9427] opened 2022-04-02 06:00 UTC
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Sometimes JSON request payload can be large. Built-in express json parser has internal limit of 100kb by default.

Can be seen on this row.
https://github.com/expressjs/body-parser/blob/master/lib/types/urlencoded.js#L53

Initialization in Nest.js application occurres here and config object is not used.

https://github.com/nestjs/nest/blob/4f91d6f4d4f56c63dfc0be1c4cdd2a0946379034/packages/platform-express/adapters/express-adapter.ts#L180

### Describe the solution you'd like

It would be reasonable to add this configuration to enable devs configure those objects.

### Teachability, documentation, adoption, migration strategy

We can enable / disable parsers in NestFactory. So if we add another interface that we can set boolean (as it is now) or the configuration object of the parser.

# main.ts
```
const app = await NestFactory.create(AppModule, {
  bodyParser: {
   enabled: true,
    json: {
      limit: '200kb',
    }
  }
});
```

### What is the motivation / use case for changing the behavior?

I came into this case, where web client had to send more data to API.

**Comment by micalevisk** [comment] 2022-04-02 15:06
duplicate of #529 

---

If you want to configure `body-parser`, disable the builtin one and add a middleware instead like this one:

```ts
import { NestMiddleware } from '@nestjs/common';
import { json as jsonBodyParser, OptionsJson } from 'body-parser';

type JsonBodyParserConfiguration = OptionsJson;

export class JsonBodyParserMiddleware implements NestMiddleware {
  private readonly options: JsonBodyParserConfiguration = {
    type: 'application/json',
    inflate: true,
    limit: '100kb',
    strict: true,
  };

  use = jsonBodyParser(this.options);
}
```

```ts
// ...
@Module({})
export class AppModule implements NestModule {
  configure(middlewareConsumer: MiddlewareConsumer): void {
    middlewareConsumer
      .apply(JsonBodyParserMiddleware)
      .forRoutes({
        path: '*',
        method: RequestMethod.ALL,
      });
   }
}
```

**Comment by kamilmysliwiec** [comment] 2022-04-04 06:57
You can also register `body-parser` middleware in the `main.ts` file. If already registered, the default body parser will be ignored.

**Closed by kamilmysliwiec** 2022-04-04 06:57 UTC
Labels: type: enhancement :wolf:, needs triage
