### ISSUE TITLE
Why Fastify getRequestUrl() platform adapter use req.url property instead of req.originalUrl like Express does ?

### ISSUE THREAD

**Issue by mohamed-badaoui** [nestjs/nest#5715] opened 2020-11-18 20:40 UTC
## Bug Report
It seems that exclude(<path>) applied for middeware cannot work properly with fastify adapter.

## Current behavior
When fastify adapter is used, exclude(<path>) applied for middleware does not work properly.
Exclude works fine with Express middleware

## Input Code

```export class JwtModule implements NestModule {
  configure(consumer: MiddlewareConsumer): void {
    consumer
      .apply(JwtMiddleware)
      .exclude(
        { path: '/account/signin', method: RequestMethod.POST },
      )
      .forRoutes(
         ...Module1Controllers,
         ...Module2Controllers,
      );
  }
}

```

## Possible Solution
It works fine with fastify adapter only if this line returns request.originalUrl;
https://github.com/nestjs/nest/blob/v7.5.4/packages/platform-fastify/adapters/fastify-adapter.ts#L263

like express adapter does:
https://github.com/nestjs/nest/blob/v7.5.4/packages/platform-express/adapters/express-adapter.ts#L107

## Environment
Nest version: 7.5.4

**Comment by kamilmysliwiec** [comment] 2020-11-19 08:01
If you face any issue, please, provide a minimum reproduction repository.

**Comment by micalevisk** [comment] 2021-05-16 23:49
@kamilmysliwiec @mohamed-badaoui @jmcdo29 
Please reopen this issue. Download the the minimum reproduction from here: https://codesandbox.io/s/jolly-haslett-ewo56?file=/README.md

---

I've changing the bellow 

https://github.com/nestjs/nest/blob/b3fb080127d2f9c8211211f6972ea92e9c2a0bb1/packages/platform-fastify/adapters/fastify-adapter.ts#L259-L260

to return `request.originalUrl` instead and it worked as expected.

**Comment by jmcdo29** [comment] 2021-05-16 23:53
@micalevisk would you mind making it a git repo? Easier to clone and work with locally

**Comment by micalevisk** [comment] 2021-05-17 00:05
> @micalevisk would you mind making it a git repo? Easier to clone and work with locally

here you go https://github.com/micalevisk/issue-5715-nestjs-fastify

**Comment by jmcdo29** [comment] 2021-05-17 01:21
I can reproduce it, and it looks like the fix suggested would do the job.

**Comment by micalevisk** [comment] 2021-05-17 01:27
> I can reproduce it, and it looks like the fix suggested would do the job. Thank you for the reproduction

ty!

but the problem of using `request.originalUrl` is that when the browser perform an `GET /favicon.ico`, express-platorm returns `/favicon.ico` while, for this solution, fastify-adapter returns `undefined` :/
see:

```
> output of ExpressAdapter#getRequestUrl: /foo
> output of ExpressAdapter#getRequestUrl: /favicon.ico


> output of FastifyAdapter#getRequestUrl: /
> the value of `request.originalUrl` in FastifyAdapter#getRequestUrl: /foo
> output of FastifyAdapter#getRequestUrl: /favicon.ico
> the value of `request.originalUrl` in FastifyAdapter#getRequestUrl: undefined
```

**Comment by mohamed-badaoui** [comment] 2021-05-17 12:37
hi,
Personally I rewrite the method like that

```
const adapter = new FastifyAdapter()
adapter.getRequestUrl = (request: CustomRequest) => {
    return request.raw ? request.raw.url : request.originalUrl || request.url;
}
```

**Comment by micalevisk** [comment] 2021-07-07 16:45
This bug still persist in Nest v8.0.0 :disappointed:

https://github.com/nestjs/nest/blob/8b9b0dfe7b6eef7491e4146b04d4caf1a7d25030/packages/platform-fastify/adapters/fastify-adapter.ts#L263-L265

**Comment by Zclhlmgqzc** [comment] 2021-07-16 19:08
see #7562

**Comment by kamilmysliwiec** [comment] 2021-07-27 10:47
Fixed in 8.0.5

**Closed by kamilmysliwiec** 2021-07-27 10:47 UTC
Labels: needs clarification
