### ISSUE TITLE
three option are not show for small screens

### ISSUE THREAD

**Issue by techmannih** [nestjs/nest#12495] opened 2023-10-03 17:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello @kamilmysliwiec ,
I found an issue in your website in which we are not able to see three option in the navbar .
please you can check and I want to work on this issue ...please assign me.

recently for small screens
![2023-10-03_23-01](https://github.com/nestjs/nest/assets/125847751/7b4db53c-7b94-4d62-9aa3-7bbe56021019)

recently for big screen

![2023-10-03_19-54](https://github.com/nestjs/nest/assets/125847751/222b05e7-8de8-4723-8ee6-a3a63d4c305d)

### Minimum reproduction code

https://github.com/nestjs/nest/issues

### Expected behavior

After solving this issue for small screens
![2023-10-03_19-54](https://github.com/nestjs/nest/assets/125847751/72a90527-a291-4968-8d52-bdd146f7d345)

### Package

- [x] I don't know. Or some 3rd-party package
- [x] <code>@nestjs/common</code>
- [x] <code>@nestjs/core</code>
- [x] <code>@nestjs/microservices</code>
- [x] <code>@nestjs/platform-express</code>
- [x] <code>@nestjs/platform-fastify</code>
- [x] <code>@nestjs/platform-socket.io</code>
- [x] <code>@nestjs/platform-ws</code>
- [x] <code>@nestjs/testing</code>
- [x] <code>@nestjs/websockets</code>
- [x] Other (see below)

### Packages versions

```json

```

### Node.js version

20v

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment] 2023-10-03 17:19
Which site is this?

**Comment by Tony133** [comment] 2023-10-03 19:39
The site should be this: https://nestjs.com/

However in `768px` resolution, so the resolution for tablets is correct and can be seen that way, the links disappear as the resolution decreases, adapting to the device (responsive).
You just need to understand whether the documentation link is correct behavior that remains viewable in this way (see screenshot) In the resolution for "tablet", you need to ask Kamil or it is a graphic bug in the responsive mode. Although it's not a bad thing that the link to the documentation remains. 🙂


<img width="1007" alt="screen-nestjs com-responsive-tablet" src="https://github.com/nestjs/nest/assets/11542387/0e0b1a0e-4a4a-4b4d-9ddb-b0ebf5c255fe">

**Comment by techmannih** [comment] 2023-10-04 01:46
> Which site is this?

Yeah @jmcdo29 , The site should be this: https://nestjs.com/

**Comment by jmcdo29** [comment] 2023-10-04 01:48
@techmannih your initial post has images of a tool by the name "Tauri", hence my question for clarification

**Comment by techmannih** [comment] 2023-10-04 01:52
Yeah, @jmcdo29 It's by mistake

**Comment by techmannih** [comment] 2023-10-04 01:52
But this is of your website

**Comment by jmcdo29** [comment] 2023-10-04 01:55
I see that, I was just explaining my initial request for clarification

**Comment by techmannih** [comment] 2023-10-04 02:00
Yes @jmcdo29 , so I want to want work on this issue ...please assign me

**Comment by jmcdo29** [comment] 2023-10-04 02:04
Chill. Let's wait for Kamil to say whether this is intentional responsive design or a bug that was overlooked. If it is a bug, no need to assign it through GitHub to anyone, just open a PR and link to the issue. If it's not a bug, well, it'll be closed

**Comment by techmannih** [comment] 2023-10-04 02:09
Okay, I will create PR

**Comment by kamilmysliwiec** [comment] 2023-10-04 06:10
That's the expected behavior.

**Closed by kamilmysliwiec** 2023-10-04 06:10 UTC
Labels: needs triage
