### ISSUE TITLE
A class injecting a provider with the same token name fails injection

### ISSUE THREAD

**Issue by jmcdo29** [nestjs/nest#9245] opened 2022-02-22 22:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

It turns out that right now, if a class (`AppService`) injects a dependency that has the same name (`@Inject('AppService')`), Nest will throw an error: `Nest can't resolve dependencies of the AppService (?). Please make sure that the argument AppService at index [0] is available in the AppModule context.`

I assume this is to prevent self injecting loops that will never actually resolve (class `AppService` injects class `AppService` inject class `AppService` etc).

This is happening here: https://github.com/nestjs/nest/blob/master/packages/core/injector/injector.ts#L434

### Minimum reproduction code

https://github.com/jmcdo29/self-injection

### Steps to reproduce

```
git clone git@github.com/jmcdo29:self-injection.git
cd self-injection
npm i
npm run start:dev
# observe error
```

### Expected behavior

Nest should only throw an error if there are no specific providers using the custom provider syntax that have the same provider name as the class.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.3.1

### Packages versions

```
platform-express version : 8.3.1
schematics version       : 8.0.6
testing version          : 8.3.1
common version           : 8.3.1
core version             : 8.3.1
cli version              : 8.2.1
```

### Node.js version

16.13.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

## Motivation for the "fix"

I've seen several users in the Discord create a wrapper class to create a custom repository via something like

```ts
@Injectable()
export class FooRepository {
  constructor(@InjectRepository(Foo) private readonly fooRepo: Repository<Foo>) {}
}
```

This results in the error message above. While I don't think this approach is necessary, we shouldn't necessarily be limiting, especially as Nest v8 allows for injecting classes by reference and not just by name anymore. 

If this is still the intention, we should make a mention in the docs that providers cannot inject providers with the same name. Namely, class providers will not be able to `@Inject(ProviderWithTheSameNameAsClass)`

**Comment by jmcdo29** [comment] 2022-02-23 00:26
Looks like this is generally related to #8894

**Comment by micalevisk** [comment] 2022-02-23 01:09
what about changing `wrapper.name === name` to `wrapper.token === name` below?

https://github.com/nestjs/nest/blob/a576a0b857f1939541a57af9babdd45ffca53e5f/packages/core/injector/injector.ts#L434

From what I've tested (only 4 scenarios) this will making self-injection throws _(which is better than crashing with not errors)_, and will allow injecting a provider with the same token name as the class name

<details>
<summary>after adding a <code>console.log</code> on that <code>lookupComponent</code> method</summary>

![image](https://user-images.githubusercontent.com/13461315/155245797-7dacc1c3-ecef-4e3e-9155-c0db537a4557.png)

</details>

**Comment by kamilmysliwiec** [comment] 2022-02-23 09:26
Yeah that's a duplicate of https://github.com/nestjs/nest/issues/8894

**Comment by micalevisk** [comment] 2022-02-23 10:45
@kamilmysliwiec to clarify, is the following considered as a self-injection after NestJS v8?

```ts
class Foo {
  constructor(@Inject('Foo') private foo: string) {}
}

@Module({
  providers: [
    {
      provide: Foo, // This token isn't the same as the one in the provider below
      useClasss: Foo,
    },
    {
      provide: 'Foo',
      useValue: 'bar',
    },
  ],
})
class AppModule {}
```

**Comment by kamilmysliwiec** [comment] 2022-02-23 11:19
@micalevisk ah thanks for pointing that out, I think I've misunderstood. That seems to be a different issue then

**Comment by micalevisk** [comment] 2022-02-23 11:31
does changing that  

`if (wrapper && wrapper.name === name) { `](https://github.com/nestjs/nest/blob/a576a0b857f1939541a57af9babdd45ffca53e5f/packages/core/injector/injector.ts#L434)

to

`if (wrapper && (wrapper.token || wrapper.name) === name) { `

makes sense? it would fix this issue

**Comment by kamilmysliwiec** [comment] 2022-02-28 15:00
Very likely yes @micalevisk, this might be a leftover from the previous behavior where we were associating providers with their stringified tokens.

**Closed** 2022-03-01 12:01 UTC
Labels: needs triage
