### ISSUE TITLE
Transient services are not instantiated (constructor is not called) when injected to middleware constructor

### ISSUE THREAD

**Issue by mrnateriver** [nestjs/nest#5884] opened 2020-12-08 09:27 UTC
## Current behavior
If a service has a `Scope.TRANSIENT` injection scope, its constructor is **not** called when the service is injected into a middleware.
However, the instance is created with a proper prototype, so it must mean that either it's created with `Object.create`, or cloned from an existing instance. I haven't done any further investigation.

## Input Code
https://github.com/mrnateriver/nestjs-transient-service-middleware

Run, take a look at the output:
```
[Nest] 9852   - 08/12/2020, 16:20:57   [NestFactory] Starting Nest application...
[Nest] 9852   - 08/12/2020, 16:20:57   TestService c-tor +21ms
[Nest] 9852   - 08/12/2020, 16:20:57   AppController c-tor, test.privateField: hello there +0ms
[Nest] 9852   - 08/12/2020, 16:20:57   [InstanceLoader] AppModule dependencies initialized +1ms
[Nest] 9852   - 08/12/2020, 16:23:18   Middleware c-tor, test.privateField: undefined +0ms
[Nest] 9852   - 08/12/2020, 16:23:18   [RoutesResolver] AppController {}: +2ms
[Nest] 9852   - 08/12/2020, 16:23:18   [RouterExplorer] Mapped {, GET} route +15ms
[Nest] 9852   - 08/12/2020, 16:23:18   [NestApplication] Nest application successfully started +135ms
```

Note that `TestService` constructor is called only once (for the controller), and private field inside the service is undefined when logged from the middleware constructor.

## Expected behavior
`TestService` constructor should be called each time it's injected to a consumer.

## Environment
```
Nest version: 7.5.5
 
For Tooling issues:
- Node version: 13.9.0
- Platform:  Windows 10
```

**Comment by kamilmysliwiec** [comment] 2020-12-08 09:35
This looks like a duplicate of https://github.com/nestjs/nest/issues/5427

**Closed by kamilmysliwiec** 2020-12-08 09:35 UTC
Labels: needs triage
