### ISSUE TITLE
HMR doesn't work on a new project

### ISSUE THREAD

**Issue by brandon-leapyear** [nestjs/nest#5835] opened 2020-12-01 01:14 UTC
## Current behavior

1. `nest new my-project`
1. `yarn install`
1. `yarn start` -- works
1. Copy/paste `webpack-hmr.config.js` as specified in "Hot reload" (https://docs.nestjs.com/recipes/hot-reload#configuration)
1. Update `start` script with hot reload command
1. `yarn start`

```
$ nest build --webpack --webpackPath webpack-hmr.config.js

 Error  Invalid options object. Watch Ignore Plugin has been initialized using an options object that does not match the API schema.
 - options[0] misses the property 'paths'. Should be:
   [RegExp | string, ...] (should not have fewer than 1 item)
   -> A list of RegExps or absolute paths to directories or files that should be ignored.
 - options[1] misses the property 'paths'. Should be:
   [RegExp | string, ...] (should not have fewer than 1 item)
   -> A list of RegExps or absolute paths to directories or files that should be ignored.
```

## Input Code

```ts
const your = (code) => here;
```

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jmcdo29** [comment] 2020-12-01 02:24
This is most likely a duplicate of #5667 and #5706 and related to using webpack v5 vs v4.

**Comment by kamilmysliwiec** [comment] 2020-12-01 07:54
`start-server-webpack-plugin` is incompatible with Webpack 5. Let's track this here ericclemmons/start-server-webpack-plugin#40 (if the fix won't be published in the next few weeks, we'll migrate away from this library in the official example).

**Closed by kamilmysliwiec** 2020-12-01 07:54 UTC
Labels: needs triage
