### ISSUE TITLE
When upgrading from 5.7.3 to 6.0.0, using FastifyAdapter produces 404 Not Found for all routes

### ISSUE THREAD

**Issue by Tsury** [nestjs/nest#1703] opened 2019-03-17 16:11 UTC
Using the default express adapter works fine.

Code:
```
import { NestFactory } from '@nestjs/core';
import { FastifyAdapter, NestFastifyApplication } from '@nestjs/platform-fastify';
import { AppModule } from './app.module';

const bootstrap = async () => {
  const app = await NestFactory.create<NestFastifyApplication>(AppModule, new FastifyAdapter());
  await app.listen(3000, '0.0.0.0');
};

bootstrap().then().catch();
```

Simply removing `FastifyAdapter` makes everything work fine again.
Tried removing `node_modules`, cleairng cache etc.

Currently reverted to 5.7.4 where everything works fine with `FastifyAdapter`

**Comment by jmcdo29** [comment] 2019-03-17 18:15
I thought this was just me and a way I had my code set up. Initializing a new nest app with `nest new fastify-test` and adding the fastify adapter doesn't seem to break it though, so far as I could tell.

**Comment by BrunnerLivio** [comment] 2019-03-17 19:51
I can reproduce this issue:
https://gist.github.com/BrunnerLivio/cd0bb683a73bfcb90d3c0ffd7dcac412

**Comment by kamilmysliwiec** [comment] 2019-03-18 08:55
Actually, this is not a bug, but the default fastify behavior after its latest major release. You need to add trailing slash to every HTTP request:

```
https://localhost:3000/cats <- WRONG
https://localhost:3000/cats/ <- OK
```

In order to ignore trailing slash, you can set a flag:

```typescript
const app = await NestFactory.create<NestFastifyApplication>(
    ApplicationModule,
    new FastifyAdapter({ ignoreTrailingSlash: true }),
  );
```
Perhaps, it's worth adding to the documentation.

**Comment by truewt** [comment] 2019-03-18 10:19
I also came across this issue and tried the proposed solution. However there is no any difference with 404 response. To reproduce the issue - I downloaded 6.0.0 archive from GitHub releases subpage and extracted the contents on my system. Then I moved to the `samples/10-fastify`, commented out controller guard for cats and ran `npm install` + `npm start`. I visited both `http://localhost:3000/cats` and `http://localhost:3000/cats/` in different browsers, with different/random sequence of entering URLs (first with trailing slash and after that without it). I'm still getting 404 and can't get the right answer with fastify - with express everything works as expected. I'm having the same problem with the endpoint which is specified for Swagger docs.

**Comment by kamilmysliwiec** [comment] 2019-03-18 10:29
@truewt thanks. For some reason it seems that app starts working correctly when you simulate the first HTTP request:

```typescript
  await app.listen(3000);
  await app
    .getHttpAdapter()
    .getInstance()
    .inject({
      method: 'GET',
      url: '/cats',
    });
```
then, each subsequent request will work. Will dig into this issue.

**Comment by kamilmysliwiec** [comment] 2019-03-18 11:27
It should be fixed in 6.0.1 :) Please, let me know if you encounter any issues.

**Comment by truewt** [comment] 2019-03-18 11:46
Now it works as expected.

Not related to this issue, but after testing routing I figured out that Swagger is not compatible with fastify after separation of express from core (so with v6). Is this ok (since after fast lookup of Swagger package, it depends on express) or should there be a fastify based Swagger package? If anything related to that should be contributed I can try to arrange my team to look at this.

**Comment by kamilmysliwiec** [comment] 2019-03-18 11:50
@truewt I'll take care of swagger module shortly. :)

**Closed by kamilmysliwiec** 2019-03-18 11:50 UTC
Labels: type: question 🙌
