### ISSUE TITLE
Terminus: Ability to get the terminus status from another class ?

### ISSUE THREAD

**Issue by appsolutegeek** [nestjs/nest#2877] opened 2019-09-03 15:53 UTC
## Is your feature request related to a problem? Please describe.
I am currently providing METRICS for Prometheus and I wish to provide a custom metrics of the current status of the Terminus statuses... I just want to be able to find out if ALL IS OK or something is failing, pretty much like calling the endpoint.

It would be great to able to inject something here and call it without going througn the endpoint

## What is the motivation / use case for changing the behavior?
 Able to provide terminus status (UP / DOWN services) to other providers throughout the system without having to calling a hosted endpoint.

**Comment by BrunnerLivio** [comment] 2019-09-03 18:43
Duplicate of [nestjs/terminus#9](https://github.com/nestjs/terminus/issues/9). We are currently starting the discussion on [nestjs/terminus#340](https://github.com/nestjs/terminus/issues/340) which should enable this feature.

**Closed by BrunnerLivio** 2019-09-03 18:43 UTC
Labels: needs triage, type: enhancement :wolf:
