### ISSUE TITLE
typescript@3.6.2 and TypeORM issue

### ISSUE THREAD

**Issue by lilacdev** [nestjs/nest#2845] opened 2019-08-29 08:32 UTC
Just a kind tip : TypeORM and typescript@3.6.2 will throw an error at compile time.
As workaround, you can use typescript@3.1.6 .

**Comment by kamilmysliwiec** [comment] 2019-08-29 09:48
Sounds like a duplicate of https://github.com/typeorm/typeorm/issues/4662

**Closed by kamilmysliwiec** 2019-08-29 09:48 UTC
Labels: needs triage
