### ISSUE TITLE
How do I get at the HttpServer-instance?

### ISSUE THREAD

**Issue by blissi** [nestjs/nest#672] opened 2018-05-13 11:27 UTC
Hallo,
I need the HttpServer-instance so that I can pass it to GraphQL's SubscriptionServer. In the sample application you are creating a new HTTP server, but I'd like it to listen at the same port as the application's main HTTP server.

Is there an easy way to do this?
I grabbed through the code and tried to inject

**Comment by kamilmysliwiec** [comment] 2018-05-13 12:37
Duplicate of #500

**Closed by kamilmysliwiec** 2018-05-13 12:37 UTC
Labels: type: duplicate :wastebasket:
