### ISSUE TITLE
Allow Module level code to be executed from CLI

### ISSUE THREAD

**Issue by maphe** [nestjs/nest#4716] opened 2020-05-01 23:46 UTC
## Is your feature request related to a problem? Please describe.
Problem is not being able to run logic from the app (modules/services) from a command line.

## Describe the solution you'd like
Allow app level code to be executed through CLI. Basically I'd like to be able to execute some code from a module (or a service) via the nest command.

## Teachability, Documentation, Adoption, Migration Strategy
The way I would see it, adding a `commands` block in the module declaration the same way controllers are defined:
```ts
@Module({
  controllers: [],
  commands: [SomeCommand],
})
```
`SomeCommand` service would basically expose a commander `program/Command` in which I could inject any other service from my module or my app.
```ts
class SomeCommand implements NestCommand {
  constructor(/* usual dependency injection stuff here */)

  public load(): Command { // from the NestCommand interface
    const program = new Command();
    program
      .command('my-command [some-option]')
      //...
      .action(() => {
        // use injected dependencies here
      });

    return program;
  }
}
```

Then I would be able to execute via CLI: `nest command my-command`. It would require to create and boot the app without an HTTP Server, manage all the dependency injection and run the relevant command.

Obviously the implementation could differ from this quick draft, but you get the idea.

## What is the motivation / use case for changing the behavior?
There are many use cases where you may want to execute code from your app from the command line. Basically any on-demand maintenance/development task. A few examples:
- developing a bull repeatable job, I want to be able to trigger it on-demand
- developing an API, I want to manually generate an access token
- running some diagnostic that requires some of the logic implemented in a module

Also having it at the module level makes the commands exportable with the module they live into. So I can export a library with a bunch of handy commands and the lib users can benefit from it.

**Comment by BrunnerLivio** [comment] 2020-05-02 00:44
Duplicate of #1117

**Closed** 2020-05-02 00:44 UTC
Labels: needs triage, type: enhancement :wolf:
