### ISSUE TITLE
Hot Reload not working due to upgrade to webpack 5

### ISSUE THREAD

**Issue by douglasgc** [nestjs/nest#5686] opened 2020-11-11 18:08 UTC
## Potential Commit/PR that introduced the regression**
https://github.com/nestjs/nest-cli/commit/ee6f823f0d6dba965a61e6c2be2f1bbcc3e96f0c
(package.json line 66)

## Describe the regression
Hot-reload does not work due to webpack update. Due to the "'start-server-webpack-plugin'" package not being compatible.

## Input Code
```json
    "typescript": "^3.6.4",
    "webpack": "4.44.2",
    "typescript": "4.0.5",
    "webpack": "5.4.0",
```

## Expected behavior/code
Create or use a compatible package and update a document so that you can implement hot-reload.

## Environment
<pre><code>
Nest version: "7.5.1"

For Tooling issues:
- Node version: 12
- Platform:  Linux

Others:

</code></pre>

**Comment by jmcdo29** [comment] 2020-11-11 18:49
Duplicate of #5667

**Closed by jmcdo29** 2020-11-11 18:49 UTC
Labels: needs triage, type: bug :sob:
