### ISSUE TITLE
useFactory error catching

### ISSUE THREAD

**Issue by alexreal1314** [nestjs/nest#5433] opened 2020-09-16 14:02 UTC
## Is your feature request related to a problem? Please describe.
We would like to be able to catch errors while initializing Typegoose and Mongoose modules.
The problem we have today is that we are running the our app in a docker swarm environment, and the service is sometimes initialized before mongoDB.

> MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at NativeConnection.Connection.openUri (C:\Users\alex\Desktop\actions_manager_service\actions_manager_service\node_modules\mongoose\lib\connection.js:823:32)
    at Mongoose.createConnection (C:\Users\alex\Desktop\actions_manager_service\actions_manager_service\node_modules\mongoose\lib\index.js:279:17)
    at InstanceWrapper.useFactory [as metatype] (C:\Users\alex\Desktop\actions_manager_service\actions_manager_service\node_modules\nestjs-typegoose\dist\typegoose-core.module.js:67:37)
    at Injector.instantiateClass (C:\Users\alex\Desktop\actions_manager_service\actions_manager_service\node_modules\@nestjs\core\injector\injector.js:292:55)
    at callback (C:\Users\alex\Desktop\actions_manager_service\actions_manager_service\node_modules\@nestjs\core\injector\injector.js:76:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

`    TypegooseModule.forRootAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: async (config: ConfigService) => {
        return {
          uri: `mongodb://${config.get('server..hostname')}/${config.get('server..name')}`,
          useNewUrlParser: true,
          useUnifiedTopology: true,
          useCreateIndex: true
        }
      }
    })`

## Describe the solution you'd like
I would like to add an error catching error to the bootstrap function or the useFactory method.
`bootstrap().catch(error => {
  logger.error(error, null, 'Bootstrap');
});`

## Teachability, Documentation, Adoption, Migration Strategy
see the above

## What is the motivation / use case for changing the behavior?
I want to log errors when initializing modules fith useFactory methods.

**Comment by jmcdo29** [comment] 2020-09-16 14:11
Duplicate of https://github.com/nestjs/nest/issues/5162. There's an open PR for it

**Closed** 2020-09-17 05:48 UTC
Labels: needs triage, type: enhancement :wolf:

**Comment by lucasaba** [comment] 2022-03-11 08:46
@alexreal1314 did you solve the initial error ? How did you fix the fact that the service is initialized before mongoDB ?
