### ISSUE TITLE
A new adapter need based on HonoJS - Bun

### ISSUE THREAD

**Issue by a4arpon** [nestjs/nest#13073] opened 2024-01-21 11:45 UTC
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Express and Fastify both runs on Nodejs and Nodejs doesn't support typescript so we need to transpile the code into Java-script code. 
Bun supports typescript and hot reload also. If you can develop a architecture for nest js that can run directly on bun using Hono server side framework this will be very helpful. Cause most of the time we faced bottle neck issue from the server. Please make a hono adapter and try to run directly nestjs on Bun runtime. Then in the build stage use bun's default compiler. 

### Describe the solution you'd like

This will be great if Nest runs directly on Bun and reduce unnecessary dependencies. Use buns default tools. 

So we need a Bun Hono Adapter

### Teachability, documentation, adoption, migration strategy

Build a adapter for hono and full support on bun runtime. 

### What is the motivation / use case for changing the behavior?

In latest era JavaScript become so popular and bun is getting so powerful day by day. Nestjs feels so good while it comes to develop JavaScript server side apps. But currently it works only on nodejs architecture. supports bun but not unitize its full power.

**Comment by micalevisk** [comment] 2024-01-21 18:07
To me this should be handled by the nestjs community until it becomes really popular (as Express and Fastify).

**Comment by micalevisk** [comment] 2024-01-21 18:57
duplicate of #13013 right?

**Comment by a4arpon** [comment] 2024-01-21 19:01
> duplicate of #13013 right?

Nope. first i searched something about this. and see some one is already posted but nest js doesn't send him any response so I made one request also.

**Comment by micalevisk** [comment] 2024-01-21 19:04
> This will be great if Nest runs directly on Bun and reduce unnecessary dependencies. Use buns default tools.

yeah, these are another thing unrelated to that issue.

**Comment by jmcdo29** [comment] 2024-01-21 19:06
> > duplicate of #13013 right?
> 
> Nope. first i searched something about this. and see some one is already posted but nest js doesn't send him any response so I made one request also. 

@a4arpon [I did give a response](https://github.com/nestjs/nest/issues/13013#issuecomment-1879757799) that the NestJS team would not be supporting this directly, but if a community member wanted to create an adapter they'd be more than welcome to

**Closed** 2024-01-23 07:57 UTC
Labels: type: enhancement :wolf:, needs triage
