### ISSUE TITLE
Configuring CORS Asynchronously

### ISSUE THREAD

**Issue by Sikora00** [nestjs/nest#6118] opened 2021-01-09 16:55 UTC
## Is your feature request related to a problem? Please describe.
The "cors" library allows us to set the [configuration asynchronously](https://github.com/expressjs/cors#configuring-cors-asynchronously). This cannot be use with enableCors method, we need to do some workarounds.

## Describe the solution you'd like
It would be great to have enableCorsAsync() or if enableCors method could receive also this option property
```typescirpt
asyncConfiguration: (req) => Promise<CorsOptions>
```

## Teachability, Documentation, Adoption, Migration Strategy
It would be great to have enableCorsAsync() or if enableCors method could receive also this option property
```typescirpt
app.enableCors({asyncConfiguration: (req) => {
  return {origin: !isInternalRequest(req)};
})
```

It should require any migration.

## What is the motivation / use case for changing the behavior?
I'm using app.enableCors() to add cors headers to responses from my application, but in some cases, I don't want them, f. ex. when the request comes from the internal network.

**Comment by jmcdo29** [comment] 2021-01-09 19:48
This should just be an update to the definition for the options of `enableCors` as whatever is passed to `enableCors` is passed directly to the cors package under the hood. Would you like to make a PR for this for the express and fastify definitions? This will require a new interface in both `platform-express` and `platform-fastify` if the two CORS packages have different options.

**Comment by Sikora00** [comment] 2021-01-10 10:53
aye Captain 🦸

**Comment by Sikora00** [comment] 2021-01-10 21:58
As I checked "fastify-cors" doesn't have a similar option to provide a dynamic configuration of the cors. As I understand you @jmcdo29 ask me to add a separated definition for ExpressAdapter.enableCors(options: ExpressCorsOptions) and FastifyAdapter.enableCors(options: FastifyCorsOptions), but what interface should be used in AbstractHttpAdapter? Something that merges all possible options or another solution?

**Comment by jmcdo29** [comment] 2021-01-10 22:00
If 'fatify-cors' doesn't have anything separate then it can stay as it is. Same for the `AbstractHttpAdapter`. Just create a specific express CORS config for the `ExpressAdapter` so that when `ExpressNestApplication` gets used the proper configs can be passed

**Comment by Sikora00** [comment] 2021-01-13 14:55
I created PR with what you have said @jmcdo29 , but I'm still wondering if we can support fastify. As I see cors can be added to fastify the same way as it works for express 
```
app.use(cors(getCorsConfig))
```
but fastify adapter does it by registering fastify-cors which expect options as an object. Could I ask what are the benefits of using fastify-cors and do we can replace it with cors library which supports async configuration?
If not maybe if anyone else will have the same case as me then that solution with `app.use(cors())` should be recommended and described in the documentation?

**Comment by jmcdo29** [comment] 2021-01-13 16:43
Do you know of a fastify cors library that supports async configuration?

**Comment by Sikora00** [comment] 2021-01-13 17:28
It looks that the 'cors' library can be used for both express and fastify https://github.com/fastify/fastify/issues/326#issuecomment-333532261

**Comment by jmcdo29** [comment] 2021-01-13 17:52
It looks like `cors` as a package does work, but `fastify-cors` was designed to give extra capabilities specifically for Fastify.

**Comment by Sikora00** [comment] 2021-01-13 18:43
Ok let see what fastify will say about that fastify/help#347

**Comment by Sikora00** [comment] 2021-01-13 21:29
@jmcdo29 xD https://github.com/fastify/help/issues/347#issuecomment-759723714
So, maybe don't close this issue yet :P 
but the PR for express can be merged already I think.

**Comment by jmcdo29** [comment] 2021-01-13 21:31
Thanks for taking initiative with that! If it gets merged in to fastify-cors and has the same API then we can revert all the adapter level changes and keep it at the abstraction level 😄

**Comment by Sikora00** [comment] 2021-01-13 21:41
For now, everything is in my hands 😈

**Comment by Sikora00** [comment] 2021-01-25 11:47
Ok, @jmcdo29 the PR is updated to support both, Express and Fastify :)

**Closed** 2021-01-26 07:26 UTC
Labels: needs triage, type: enhancement :wolf:
