### ISSUE TITLE
v7 error when run start:dev using openapi (swagger)

### ISSUE THREAD

**Issue by Gabrielvt14** [nestjs/nest#7518] opened 2021-07-11 17:46 UTC
## Bug Report
Error when try run start:dev using openapi (swagger)

## Current behavior
When I perform the configuration described in the documentation (https://docs.nestjs.com/#installation) and the openapi configuration (https://docs.nestjs.com/openapi/introduction#installation).
I try to run the api, and I get the following error:
```
[14:38:39] File change detected. Starting incremental compilation...

[14:38:39] Found 0 errors. Watching for file changes.

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '@nestjs/core/router/route-path-factory'
Require stack:
- /home/gabriel/Documentos/Projetos/tests/nest/testing-v7/node_modules/@nestjs/swagger/dist/swagger-explorer.js
- /home/gabriel/Documentos/Projetos/tests/nest/testing-v7/node_modules/@nestjs/swagger/dist/swagger-scanner.js
- /home/gabriel/Documentos/Projetos/tests/nest/testing-v7/node_modules/@nestjs/swagger/dist/swagger-module.js
- /home/gabriel/Documentos/Projetos/tests/nest/testing-v7/node_modules/@nestjs/swagger/dist/index.js
- /home/gabriel/Documentos/Projetos/tests/nest/testing-v7/node_modules/@nestjs/swagger/index.js
- /home/gabriel/Documentos/Projetos/tests/nest/testing-v7/dist/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/gabriel/Documentos/Projetos/tests/nest/testing-v7/node_modules/@nestjs/swagger/dist/swagger-explorer.js:8:30)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/gabriel/Documentos/Projetos/tests/nest/testing-v7/node_modules/@nestjs/swagger/dist/swagger-explorer.js',
    '/home/gabriel/Documentos/Projetos/tests/nest/testing-v7/node_modules/@nestjs/swagger/dist/swagger-scanner.js',
    '/home/gabriel/Documentos/Projetos/tests/nest/testing-v7/node_modules/@nestjs/swagger/dist/swagger-module.js',
    '/home/gabriel/Documentos/Projetos/tests/nest/testing-v7/node_modules/@nestjs/swagger/dist/index.js',
    '/home/gabriel/Documentos/Projetos/tests/nest/testing-v7/node_modules/@nestjs/swagger/index.js',
    '/home/gabriel/Documentos/Projetos/tests/nest/testing-v7/dist/main.js'
  ]
}
```

## Environment

<pre><code>
// using NestJS v7
// package.json
{
  "name": "testing-v7",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^7.6.18",
    "@nestjs/core": "^7.6.18",
    "@nestjs/platform-express": "^7.5.1",
    "@nestjs/swagger": "^5.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^6.6.7",
    "swagger-ui-express": "^4.1.6"
  },
  "devDependencies": {
    "@nestjs/cli": "^7.5.1",
    "@nestjs/schematics": "^7.1.3",
    "@nestjs/testing": "^7.5.1",
    "@types/express": "^4.17.8",
    "@types/jest": "^26.0.15",
    "@types/node": "^14.14.6",
    "@types/supertest": "^2.0.10",
    "@typescript-eslint/eslint-plugin": "^4.6.1",
    "@typescript-eslint/parser": "^4.6.1",
    "eslint": "^7.12.1",
    "eslint-config-prettier": "7.1.0",
    "eslint-plugin-prettier": "^3.1.4",
    "jest": "^26.6.3",
    "prettier": "^2.1.2",
    "supertest": "^6.0.0",
    "ts-jest": "^26.4.3",
    "ts-loader": "^8.0.8",
    "ts-node": "^9.0.0",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^4.0.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

</code></pre>

**Comment by jmcdo29** [comment] 2021-07-11 17:48
Duplicate of nestjs/swagger#1433

**Closed by jmcdo29** 2021-07-11 17:48 UTC
Labels: needs triage

**Comment by Gabrielvt14** [comment] 2021-07-11 17:57
upgrading to v8 resolved the issue, thanks

**Comment by webcat12345** [comment] 2021-07-15 19:16
Thank you.

**Comment by FreyDv** [comment] 2022-05-08 04:43
In 2022 got the same problem with the swager. Maybe the problem is that I'm just learning. But I tried to install different versions of `@nestjs/common` and `@nestjs/core` including older **V8** but it didn't help me. And the most interesting thing is that if I create a new empty project with everything working for me, including the **swager**. But after a couple of lines of code, this error is thrown again and the server crashes.

![image](https://user-images.githubusercontent.com/61236987/167281912-db3e233e-099c-4945-bd41-e80b63723f0e.png)
![image](https://user-images.githubusercontent.com/61236987/167282110-d60dfd40-cc8e-494e-974b-6f2b540cdba0.png)

**Comment by jmcdo29** [comment] 2022-05-08 19:42
@FreyDv this looks like a different issue. Please create a [minimum reproduction repository](https://minimum-reproduction.wtf) and open a new issue.
