### ISSUE TITLE
onModuleInit change the scope

### ISSUE THREAD

**Issue by cojack** [nestjs/nest#108] opened 2017-07-11 08:44 UTC
I think this is urgent problem @kamilmysliwiec , how to reproduce?

```typescript
import {Component, Logger} from '@nestjs/common';
import {OnModuleInit} from '@nestjs/common/interfaces/modules';

@Component()
export default class TestComponent implements OnModuleInit {
	private flag = false;
	private logger = new Logger(TestComponent.name);
	constructor() {
		this.logger.log('Constructor');
		this.showFlagValue();
		setTimeout(() => {
			this.logger.log('Constructor');
			this.showFlagValue();
		}, 4000);
	}

	onModuleInit() {
		setTimeout(() => {
			this.logger.log('onModuleInit');
			this.flag = true;
			this.showFlagValue();
		}, 1000);
	}

	private showFlagValue() {
		this.logger.log(`Flag value: ${this.flag}`);
	}
}
```

Output:
```
[Nest] 16820   - 7/11/2017, 10:37:22 AM   [TestComponent] Constructor
[Nest] 16820   - 7/11/2017, 10:37:22 AM   [TestComponent] Flag value: false
[Nest] 16820   - 7/11/2017, 10:37:23 AM   [TestComponent] onModuleInit
[Nest] 16820   - 7/11/2017, 10:37:23 AM   [TestComponent] Flag value: true
[Nest] 16820   - 7/11/2017, 10:37:26 AM   [TestComponent] Constructor
[Nest] 16820   - 7/11/2017, 10:37:26 AM   [TestComponent] Flag value: false
```

This can be fixed in the code by: 

```typescript
	constructor() {
		this.onModuleInit = this.onModuleInit.bind(this);
	}
```

But I don't think it's the best way to achieve this.

The third output with Flag value should be true.

**Comment by benbayard** [comment] 2017-07-12 20:54
I had this problem as well. I recommend using `@autobind` from `core-decorators`

**Comment by cojack** [comment] 2017-07-13 06:35
@benbayard but it should not happen

**Comment by kamilmysliwiec** [comment] 2017-07-16 12:49
Hey @cojack,
That's why you should avoid any additional logic inside constructor. Instead of this, there's `onModuleInit` lifecycle hook :smiley: The bug should be fixed in the nearest release. Thanks for reporting

**Comment by kamilmysliwiec** [comment] 2017-11-03 15:30
Hi @cojack,
So I have spent some time on this bug and the issue isn't with the `onModuleInit` hook, but rather with async operations (such as XHR requests, setTimeout..) called from `constructor`. It's possible to fix this with the monkey patching, but I don't think whether it makes sense. Basically, any async code called from the constructor isn't a good practice and is a bad pattern, that's why we have the `onModuleInit` hook. I think it'd be better to leave this as it is.

**Closed** 2017-11-03 15:34 UTC
Labels: bug, todo
