### ISSUE TITLE
VSCode debug: can not find module

### ISSUE THREAD

**Issue by FourLeafClover** [nestjs/nest#883] opened 2018-07-17 03:20 UTC
npm run start is ok and can also run the project。 but when i debug the error console show me can not find module。

Note：if i use import {AppModule} from './app.module'   it will be ok. but when  import {AppModule} from 'app.module'(just like the blow pictures). it will tell me that cannot find the app.module.

![image](https://user-images.githubusercontent.com/8449788/42799341-17397be6-89ca-11e8-8b7d-7b049dabe916.png)

![image](https://user-images.githubusercontent.com/8449788/42794724-fdc552f0-89b2-11e8-809a-bbe5b767e4fd.png)

this is my lanch.json

{
  // 使用 IntelliSense 了解相关属性。 
  // 悬停以查看现有属性的描述。
  // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "启动程序",
      "protocol": "inspector",
      "sourceMaps": true,
      "stopOnEntry": true,
      "console": "internalConsole",
      "program": "${workspaceFolder}\\src\\main.ts",
      "preLaunchTask": "tsc: build - tsconfig.json",
      "outFiles": [
        "${workspaceFolder}/dist/**/*.js"
      ]
    }
  ]
}

**Comment by chanlito** [comment] 2018-07-17 04:13
@FourLeafClover this issue has nothing to do with Nest.js, you should check on typescript config `paths` & module resolution.

**Comment by FourLeafClover** [comment] 2018-07-17 06:01
@chanlito  I know。 but I used the default tsconfig.json of nestjs。so, i don't konw how to config my tsconfig.json to solve this issue ，can you help me? thanks? this is my tsconfig.json.
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": false,
    "noImplicitAny": false,
    "removeComments": true,
    "noLib": false,
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es6",
    "sourceMap": true,
    "allowJs": true,
    "outDir": "./dist",
    "baseUrl": "./src"
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts"
  ]
}

**Comment by BrunnerLivio** [comment] 2018-07-17 08:19
Maybe try `import { AppModule } from './app.module';`?

**Comment by FourLeafClover** [comment] 2018-07-18 08:58
@BrunnerLivio because some of our co-workers used IntelliJ idea, they used import like this  ‘app.modules’, 'services/???.service.ts' and 'controller/???.controller.ts'。 I alse think this way  import is good。use relative path to import is difficult to read。Just like vue-cli, also import file like @/path（not '../../）

**Comment by BrunnerLivio** [comment] 2018-07-18 10:16
@FourLeafClover 
Can you close this issue? This is not Nest related.

---

In general you use inside the application relative imports e.g. `import * form './app.module'`. In TypeScript, if you use non-relative imports e.g. `import * from 'jquery'`, it looks up inside your `node_modules` folder. 

The approach from frameworks like nest, angular or vue with the `@`-prefix is a different story. `@`-prefix means the packages are scoped. [Read more here](https://stackoverflow.com/questions/36667258/what-is-the-meaning-of-the-at-prefix-on-npm-packages). I would only use this, if I want to make complicated modular software. It is quite hard to setup the architecture for scoped packages.

If you do not like to write a lot of `../../` you can still use [TypeScript path aliases](https://medium.com/@caludio/how-to-use-module-path-aliases-in-visual-studio-typescript-and-javascript-e7851df8eeaa).

Also check out the [TypeScript module resolution](https://www.typescriptlang.org/docs/handbook/module-resolution.html)

**Comment by AlariCode** [comment] 2018-07-18 10:43
If you want to use import like you showed you can use https://www.npmjs.com/package/tsconfig-paths. Just install package and change start script by registering it: -r tsconfig-paths/register

**Comment by victorschinaider** [comment] 2018-07-18 15:20
I think this is NestJs related. It'll be good if there is some default configuration to debug NestJs in documentation, in tests context and app context. `tsconfig-paths` already comes by default in `start:dev` script. But, then if you use `npm run start:prod`, problems will appear, the user manually has to configure the 'tsconfig` to has the expected behavior of nest. i think it just need to define a default behavior to resolve these problems.

**Comment by FourLeafClover** [comment] 2018-07-20 01:36
@BrunnerLivio  OK, I closed this issue. Thanks

**Closed** 2018-07-20 01:37 UTC

**Comment by IgorSzymanski** [comment] 2018-08-17 08:36
I know the issue is closed, but wanted to share my approach:
```
npm install --save import module-alias
```
In `main.ts`, line 1:
```
import 'module-alias/register'
```

`tsconfig.json`:
```
    "outDir": "./dist",
    "baseUrl": "./src",
    "paths": {
      "~/*": ["*"]
    }
```

`package.json`:
```
  "_moduleAliases": {
    "~": "./dist"
  },
```

Just make sure the path in `package.json` is the same as `outDir` in `tsconfig.json` (NOT `paths`), so the paths are resolved correctly in production.
