### ISSUE TITLE
WebSockets can't work when initializing for multiple simultaneous servers

### ISSUE THREAD

**Issue by sboisse** [nestjs/nest#5407] opened 2020-09-11 07:58 UTC
## Current behavior

We want to support both HTTP and HTTPS simultaneously so we are following instructions described here: https://docs.nestjs.com/faq/multiple-servers

We also set a `WsAdapter` before calling `app.Init()` because we want to use web sockets. However, when we do this, all websocket upgrades fail to execute properly, so the websocket handshake fails and the connection is not successfully established with the browser. The browser receives `200 OK` as a response, and throws an error.

We modified our code so we would supply the http server in the `WsAdapter` constructor instead of the Nest application, and it works.

But we want this to work for HTTPS as well. Since a single server can be supplied to the adapter, and since a single adapter can be supplied to Nest app, websocket handshakes cannot work for both HTTP and HTTPS at the same time.

How can we get this to work for both HTTP and HTTPS simultaneously?

## Input Code

```ts
    const server = express();
    const app = await NestFactory.create(AppModule, new ExpressAdapter(server));

    const httpServer = http.createServer(server);
    const httpWebSocketAdapter = new WsAdapter(httpServer);
    app.useWebSocketAdapter(httpWebSocketAdapter );

    httpsServer = https.createServer(httpsConfiguration, server);
    const httpsWebSocketAdapter = new WsAdapter(httpsServer);
    app.useWebSocketAdapter(httpsWebSocketAdapter ); // This overwrites the previous useWebSocketAdapter() for http

    await app.init();
    
    httpServer.listen(80);
    httpsServer.listen(443);
```

## Expected behavior

We would need to be able to supply several servers to the WsAdapter, or we would need to be able to supply several WsAdapters to the Nest app, one for each server we are dealing with.

## Environment

<pre><code>
Nest version: 7.4.2

 
For Tooling issues:
- Node version: 14.3.0  
- Platform:  Windows 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment] 2020-09-14 06:57
Sounds like a duplicate of this https://github.com/nestjs/nest/issues/4968 issue?

**Comment by sboisse** [comment] 2020-09-14 09:20
Not the same issue at all. They get a crash. We don't. Our problem is about
ws handshakes no longer working for all but one of our multi-servers
because we can supply only one of those to the wsadapter. This is not what
their issue is taking about at all.

**Comment by kamilmysliwiec** [comment] 2020-11-16 11:00
https://github.com/nestjs/nest/issues/5691#issuecomment-727884401

**Closed by kamilmysliwiec** 2020-11-16 11:00 UTC
Labels: needs triage
