### ISSUE TITLE
NestJS does not await asynchronous shutdown hooks in some circumstances

### ISSUE THREAD

**Issue by andrew-sol** [nestjs/nest#9649] opened 2022-05-23 11:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I use [JaniAnttonen/winston-loki](https://github.com/JaniAnttonen/winston-loki) package.

After creating a transport, NestJS stops awaiting shutdown hooks. `app.enableShutdownHooks()` is enabled.
See the reproduction code repo.

app.module.ts:
```ts
import { Logger, Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';

@Module({
  imports: [],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {
  private readonly logger = new Logger(AppModule.name);

  async beforeApplicationShutdown(): Promise<void> {
    this.logger.log(1);

    await new Promise((resolve) => setTimeout(resolve, 1000));

    this.logger.log(2);
  }
}
```

main.ts:
```ts
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import LokiTransport from 'winston-loki';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  app.enableShutdownHooks();

  // comment out the following statement and shutdown hooks will be awaited
  const lokiTransport = new LokiTransport({
    host: 'http://qweasd',
  });

  await app.listen(3000);
}

bootstrap();
```

Only the first log appears.

### Minimum reproduction code

https://github.com/andrew-sol/nestjs-reproduction-1

### Steps to reproduce

1. `yarn install --frozen-lockfile` or `npm install`
2. `yarn start:dev` or `npm run start:dev`
3. `Ctrl+C`

### Expected behavior

Both logs from the shutdown hook should be printed.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

[JaniAnttonen/winston-loki](https://github.com/JaniAnttonen/winston-loki)

### NestJS version

8.4.5

### Packages versions

@nestjs/cli@8.2.6
@nestjs/common@8.4.5
@nestjs/core@8.4.5
@nestjs/platform-express@8.4.5
@nestjs/schematics@8.0.11
@nestjs/testing@8.4.5

### Node.js version

16.14.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment] 2022-05-23 11:18
I believe this is duplicate of https://github.com/nestjs/nest-cli/issues/1487

**Comment by kamilmysliwiec** [comment] 2022-05-23 11:19
`winston-loki` uses `async-exit-hook` which overrides the default framework's behavior. This issue should be reported there (in the `winston-loki` repo) instead. There's nothing we can do on the NestJS side.

**Closed by kamilmysliwiec** 2022-05-23 11:19 UTC
Labels: needs triage
