### ISSUE TITLE
Test.createTestingModule leaves open handle due to xxh32

### ISSUE THREAD

**Issue by urugator** [nestjs/nest#11072] opened 2023-02-07 18:25 UTC
### Did you read the migration guide?

- [ ] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Potential Commit/PR that introduced the regression

d323edbab9b1f92bb4ef661bb5dd5caee2cce553

### NestJS version

9.0.0 -> 9.3.5

### Describe the regression

After upgrading from 9.0.0 to 9.3.5, tests are randomly reporting: "Jest did not exit one second after the test run has completed."
After running with `--detectOpenHandles`
```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  CustomGC

    > 1 | import { Test } from '@nestjs/testing';
        | ^
      2 |
      3 | Test.createTestingModule({});
      4 |

      at Runtime._loadModule (../../node_modules/jest-runtime/build/index.js:1218:29)
      at Object.<anonymous> (../../node_modules/@node-rs/xxhash/index.js:64:29)
      at Object.<anonymous> (../../node_modules/@nestjs/core/inspector/deterministic-uuid-registry.js:4:18)
      at Object.<anonymous> (../../node_modules/@nestjs/core/injector/instance-wrapper.js:11:24)
      at Object.<anonymous> (../../node_modules/@nestjs/core/injector/injector.js:14:28)
      at Object.<anonymous> (../../node_modules/@nestjs/core/injector/module-ref.js:8:20)
      at Object.<anonymous> (../../node_modules/@nestjs/core/injector/lazy-module-loader/lazy-module-loader.js:5:22)
      at Object.<anonymous> (../../node_modules/@nestjs/core/inspector/serialized-graph.js:8:30)
      at Object.<anonymous> (../../node_modules/@nestjs/core/injector/container.js:6:28)
      at Object.<anonymous> (../../node_modules/@nestjs/testing/testing-module.builder.js:6:21)
      at Object.<anonymous> (../../node_modules/@nestjs/testing/test.js:5:34)
      at Object.<anonymous> (../../node_modules/@nestjs/testing/index.js:11:22)
      at Object.<anonymous> (test/foo.spec.ts:1:1)
```
Investigating further, noticed this recent change
https://github.com/nestjs/nest/commit/d323edbab9b1f92bb4ef661bb5dd5caee2cce553
So I tried to run `xxh32` directly:
```ts
import { xxh32 } from '@node-rs/xxhash';
xxh32('foobarbaz');
```
producing similar output
```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:


    > 1 | import { xxh32 } from '@node-rs/xxhash';
        | ^
      2 | xxh32('foobarbaz');
      3 | //import { Test } from '@nestjs/testing';
      4 |

      at Runtime._loadModule (../../node_modules/jest-runtime/build/index.js:1218:29)
      at Object.<anonymous> (../../node_modules/@node-rs/xxhash/index.js:64:29)
      at Object.<anonymous> (test/foo.spec.ts:1:1)
```
So I assume it's due to the uuid -> xxhash change.

### Expected behavior

Jest exits properly.

**Comment by micalevisk** [comment] 2023-02-07 18:29
duplicate of #11071

**Closed by micalevisk** 2023-02-07 18:29 UTC
Labels: type: bug :sob:, needs triage

**Comment by H4ad** [comment] 2023-02-07 19:05
Hey @urugator, thanks for creating an issue, we are working to remove the dependency in this version.

Also, I think you could create the same issue at https://github.com/napi-rs/node-rs/issues, I don't think they know that the package has a potential memory leak.

**Comment by kamilmysliwiec** [comment] 2023-02-07 19:24
@urugator would you like to create an issue here too https://github.com/napi-rs/node-rs/issues?

**Comment by urugator** [comment] 2023-02-07 22:10
Done https://github.com/napi-rs/node-rs/issues/658
