### ISSUE TITLE
NestJS with Fastify is not working well

### ISSUE THREAD

**Issue by maheraldous** [nestjs/nest#9739] opened 2022-06-06 19:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello I am new here and just started to use NestJS and I want to use it with Fastify but I feel that the NestJS dose not really care about Fastify because the moment I followed the steps in the NestJS I got many errors and unupdated code and packages.

![image](https://user-images.githubusercontent.com/41970874/172233243-0f4f8043-5037-4700-9432-019a77fcc000.png)

As you see when I run `npm run start` it work somethimes but then it won't work and I really want to use fastify but it didn't work here I am leaving NestJS since I don't really like to use two things in same place. It would be better if I use Express or Fastify without NestJS but NestJS need the help with one of them and it's too bad. I tried to update the packages manually but nothing happen.

I added this code to package.json from one of the issue where here
`  "overrides": {
    "@nuxtjs/opencollective": "/dev/null"
  },`

But it dose not solve the problem. Also some Fastify packages like `@fastify/formbody` must be updated

### Minimum reproduction code

I don't have thins on the interned

### Expected behavior

Working with 0 errors since its a freash new app.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

```json
{
  "name": "nestjs-server",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@fastify/formbody": "^7.0.0",
    "@nestjs/common": "^8.4.6",
    "@nestjs/core": "^8.4.6",
    "@nestjs/platform-express": "^8.4.6",
    "@nestjs/platform-fastify": "^8.4.6",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "fastify-formbody": "^5.3.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.5.5"
  },
  "overrides": {
    "@nuxtjs/opencollective": "/dev/null"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.2.6",
    "@nestjs/schematics": "^8.0.11",
    "@nestjs/testing": "^8.4.6",
    "@types/express": "^4.17.13",
    "@types/jest": "28.1.1",
    "@types/node": "^17.0.40",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.27.1",
    "@typescript-eslint/parser": "^5.27.1",
    "eslint": "^8.17.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.1.0",
    "prettier": "^2.6.2",
    "source-map-support": "^0.5.21",
    "supertest": "^6.2.3",
    "ts-jest": "28.0.4",
    "ts-loader": "^9.3.0",
    "ts-node": "^10.8.1",
    "tsconfig-paths": "4.0.0",
    "typescript": "^4.7.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

v18.3.0.

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment] 2022-06-06 19:45
please share some minimum repro. Also, _warnings_ aren't errors.

> @fastify/formbody must be updated

duplicate of #9738

**Comment by maheraldous** [comment] 2022-06-09 16:54
> Since fastify@4.0.0 is out now this warning goes from warning to error. The related PR does not update fastify so we should downgrade fastify and its related packages.

This is not an option we need to follow the fastify or we will get crash in the future

**Comment by jghowe** [comment] 2022-06-10 03:37
FYI, we use fastify also and recently tried to update to `8.4.6` and got these errors in our tests.

```
    Keyword [object Object] is not a valid identifier

      2367 |       ];
      2368 |
    > 2369 |       const res = await app.inject({
           |                             ^
      2370 |         headers: {
      2371 |           authorization: `Bearer ${testJwt}`,
      2372 |         },

      at Ajv.addKeyword (node_modules/ajv/lib/keyword.js:30:11)
      at Object.<anonymous> (node_modules/fastify/node_modules/light-my-request/index.js:30:5)
      at Object.inject (node_modules/fastify/fastify.js:441:24)
      at Proxy.inject (node_modules/@nestjs/platform-fastify/adapters/fastify-adapter.js:190:30)
      at Object.<anonymous> (src/e2e/user-surveys.v1.e2e-spec.ts:2369:29)
```
   
It seems to be related to the recent update of `light-my-request`.  When I went back down to `8.4.5` the problem went away.

**Comment by kamilmysliwiec** [comment] 2022-06-13 10:16
This will be fixed in the next major release of nestjs (v9). See: https://github.com/nestjs/nest/pull/9588

**Closed by kamilmysliwiec** 2022-06-13 10:16 UTC
Labels: needs triage
