### ISSUE TITLE
Global request scoped exception filters don't catch built-in exceptions

### ISSUE THREAD

**Issue by amrsalama** [nestjs/nest#6429] opened 2021-02-17 10:33 UTC
## Current behavior
Global custom exception filters with `scope: Scope.REQUEST` catch only custom exceptions but built-in exceptions (e.g. NotFoundException) are handled by the built-in filter.

## Input Code

```ts
// all-exceptions.filter.ts
@Catch()
export class AllExceptionsFilter implements ExceptionFilter {
  catch(exception: unknown, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse();
    const request = ctx.getRequest();

    const status =
      exception instanceof HttpException
        ? exception.getStatus()
        : HttpStatus.INTERNAL_SERVER_ERROR;

    response.status(status).json({
      statusCode: status,
      timestamp: new Date().toISOString(),
      path: request.url,
    });
  }
}
```

```ts
// custom.exception.ts
export class CustomException extends HttpException {
  constructor() {
    super('Forbidden', HttpStatus.FORBIDDEN);
  }
}
```

```ts
// app.controller.ts
@Controller()
export class AppController {
  @Get()
  getHello(): string {
    throw new CustomException();
  }
}
```

```ts
// app.module.ts
@Module({
  imports: [],
  controllers: [AppController],
  providers: [
    {
      provide: APP_FILTER,
      useClass: AllExceptionsFilter,
      scope: Scope.REQUEST,
    },
  ],
})
export class AppModule {}
```

Reproduction repo: https://github.com/amrsalama/nestjs-global-request-scoped-filters-issue

## Expected behavior
Calling `GET /` works as expected, custom exception caught by the custom filter.
```json
{
    "statusCode": 403,
    "timestamp": "2021-02-17T10:28:00.926Z",
    "path": "/"
}
```

But calling `GET /404` doesn't work as expected, the `NotFoundException` is caught by the built-in filter.
```json
{
    "statusCode": 404,
    "message": "Cannot GET /404",
    "error": "Not Found"
}
```

If we removed `scope: Scope.REQUEST,` the `NotFoundException` will be caught by the custom filter.

## Environment

<pre>
<code>
Nest version: 7.5.1
Node version: v12.15.0
</code>
</pre>

**Comment by amrsalama** [comment] 2021-02-17 10:48
The real scenario why using a request-scoped global filter is to inject a request-scoped logger service.
This is a follow-up to #4676

**Comment by Tony133** [comment] 2021-02-17 10:52
Hi @amrsalama, I recommend that you leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you reported.

**Comment by kamilmysliwiec** [comment] 2021-02-17 11:00
Please provide a minimum reproduction repository.

**Comment by amrsalama** [comment] 2021-02-17 11:00
@Tony133  @kamilmysliwiec updated with a reproduction repository.
Reproduction repo: https://github.com/amrsalama/nestjs-global-request-scoped-filters-issue

**Comment by kamilmysliwiec** [comment] 2021-02-17 15:00
Oh I see what you mean. The "not found handler" that NestJS automatically registers upon the application bootstrap is just a simple, **static** middleware (express or fastify) function that processes all requests that didn't match any of routes registered through controller classes. Since it's **static** and does not have any dependencies (+ it's defined as function, not a class), it's detached from the IoC container and that means anything that requires DI won't be applied (request-scoped global interceptors/guards/filters etc). 

To workaround this, you can define your filter as **statically-scoped** and then use a technique described here https://docs.nestjs.com/fundamentals/module-ref#resolving-scoped-providers to dynamically create a DI container sub-tree.

**Closed by kamilmysliwiec** 2021-02-17 15:00 UTC
Labels: needs clarification

**Comment by amrsalama** [comment] 2021-02-18 19:23
Thanks, @kamilmysliwiec, I'll put the workaround here in case someone need it.
```ts
// app.service.ts
@Injectable({
  scope: Scope.REQUEST,
})
export class AppService {
  constructor(@Inject(REQUEST) private request: Request) {}

  getUrl(): string {
    return this.request.url;
  }
}

```

```ts
// all-exceptions.filter.ts
@Catch()
export class AllExceptionsFilter implements ExceptionFilter {
  constructor(private moduleRef: ModuleRef) {}

  async catch(exception: unknown, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse();
    const request = ctx.getRequest();

    const contextId = ContextIdFactory.create();
    this.moduleRef.registerRequestByContextId(request, contextId);
    const appService = await this.moduleRef.resolve(AppService, contextId);

    const status =
      exception instanceof HttpException
        ? exception.getStatus()
        : HttpStatus.INTERNAL_SERVER_ERROR;

    response.status(status).json({
      statusCode: status,
      timestamp: new Date().toISOString(),
      path: appService.getUrl(),
    });
  }
}
```

```ts
// app.module.ts
@Module({
  imports: [],
  controllers: [AppController],
  providers: [
    AppService,
    {
      provide: APP_FILTER,
      useClass: AllExceptionsFilter,
    },
  ],
})
export class AppModule {}
```

**Comment by kamilmysliwiec** [comment] 2021-02-19 07:38
Amazing, thanks for sharing @amrsalama, appreciate it a lot!
