### ISSUE TITLE
Express in not found when installing with pnpm

### ISSUE THREAD

**Issue by morbargig** [nestjs/nest#10829] opened 2023-01-08 15:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

clone new project
install dependencies with pnpm
use express for few features 
get error module not found

`ERROR in ./apps/mor/src/main.ts 11:18-36
Module not found: Error: Can't resolve 'express' in '/Users/morbargig/Desktop/Projects/ideo/Phoenix/B2B/test-2/apps/mor/src'

webpack compiled with 1 error (532660906b382153)
There was an error with the build. See above.
/Users/morbargig/Desktop/Projects/ideo/Phoenix/B2B/test-2/dist/apps/mor/main.js was not restarted.
Type-checking in progress...
ERROR in ./apps/mor/src/main.ts:9:34
TS2307: Cannot find module 'express' or its corresponding type declarations.
     7 | import { NestFactory } from '@nestjs/core';
     8 | import { AppModule } from './app/app.module';
  >  9 | import { json, urlencoded } from 'express';
       |                                  ^^^^^^^^^
    10 |
    11 | async function bootstrap() {
    12 |   const app = await NestFactory.create(AppModule);

Found 1 error in 2352 ms.`

when install via npm everything works fine

![image](https://user-images.githubusercontent.com/51287453/211203541-a7f4a807-4177-47fd-9965-1c0c1bffe172.png)

### Minimum reproduction code

https://github.com/morbargig/repo-for-nestjs-bug

### Steps to reproduce

// not working
1. git clone https://github.com/morbargig/repo-for-nestjs-bug.git
2. pnpm install
3. pnpm nx run mor:serve

// working
1. git clone https://github.com/morbargig/repo-for-nestjs-bug.git
2. npm install
3. npx nx run mor:serve

### Expected behavior

Expect the code to understand the dependency of the package `@nestjs/platform-express`
and it @types from express, which in NPM works just fine.

Is the package @nestjs/platform-express depended on `express`
it can also make sure the dependency clean to any package manager.
Or even export the types and features of it.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.2.1

### Packages versions

```json
{
  "name": "test-2",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {},
  "private": true,
  "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.0.0",
    "tslib": "^2.3.0"
  },
  "devDependencies": {
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@nrwl/eslint-plugin-nx": "15.4.5",
    "@nrwl/jest": "15.4.5",
    "@nrwl/linter": "15.4.5",
    "@nrwl/nest": "15.4.5",
    "@nrwl/node": "15.4.5",
    "@nrwl/nx-cloud": "latest",
    "@nrwl/workspace": "15.4.5",
    "@types/jest": "28.1.1",
    "@types/node": "18.7.1",
    "@typescript-eslint/eslint-plugin": "^5.36.1",
    "@typescript-eslint/parser": "^5.36.1",
    "eslint": "~8.15.0",
    "eslint-config-prettier": "8.1.0",
    "jest": "28.1.1",
    "jest-environment-jsdom": "28.1.1",
    "nx": "15.4.5",
    "prettier": "^2.6.2",
    "ts-jest": "28.0.5",
    "ts-node": "10.9.1",
    "typescript": "~4.8.2"
  }
}

```

### Node.js version

v19.4.0

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

### Other

I am using NestJS in my enterprise production products.
So this is very important to me. 
Any help will be very handy.

**Comment by micalevisk** [comment] 2023-01-08 15:18
we can't do nothing on nestjs side since this is an issue with your project structure.

### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
  ![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)

**Comment by micalevisk** [comment] 2023-01-08 17:04
duplicate of #10808

**Closed by micalevisk** 2023-01-08 17:04 UTC
Labels: needs triage

**Comment by jmcdo29** [comment] 2023-01-08 19:14
I'll explain this here as I don't want to see another issue opened. Next time, please consider what others have already said about _where_ to receive support.

PNPM is a different package manager that treats packages differently than `npm` or `yarn` does. If you run `pnpm info @nestjs/platform-express` you'll see that 1express` is indeed a dependency so it will be installed. To pnpm that means it gets installed under `node_modules/.pnpm/@nestjs/platform-express/node_modules/express` (or something very close to that, probably with a version and hash). pnpm also symlinks `node_modules/@nestjs/platform-express` to `node_modules/.pnpm/@nestjs/platform-express` so that `node` and `typescript` both can go to `node_modules/@nestjs/platform-express` and get the dependency information and know how to read everything.

What npm and yarn do is just install everything into `node_modules`, peer deps and all, so you are able to access peer deps directly using `require/import from 'peerDep'` and it's all good. This isn't the case with pnpm and it never will be due to the node_modules structure it keeps for the sake of sanity.

This isn't an issue with pnpm or with Nest, but with how you're expecting to use a peer dep/dep or a dep without installing it yourself.
