### ISSUE TITLE
[Question] Access container before launching an app.

### ISSUE THREAD

**Issue by thohoh** [nestjs/nest#229] opened 2017-11-05 06:44 UTC
Hello.

In my application I want to configure express app before launching it (all the 3rd party middleware, sessions, passport, hostname and port).
The configuration provider is in my common module and it depends on the environment service that is injected into it. Is there way to do this kind of routine thing with nest container?

Thanks.

**Comment by shekohex** [comment] 2017-11-06 16:37
Maybe this will help 

[NestJS FAQ [_express-instance_]](https://docs.nestjs.com/faq/express-instance)

**Comment by maxmalov** [comment] 2017-11-12 09:55
Hey, one more interesting case is accessing configuration service or logger before launching the application. For example, the port is stored in the configuration file, so I want to pick it from my configuration service instead of hardcoding it anywhere in the application. Any ideas how it can be resolved?

**Comment by kamilmysliwiec** [comment] 2017-11-19 19:10
Hey @thohoh,
In fact, it's a duplicate of https://github.com/nestjs/nest/issues/201. This feature is **in progress*. 🙂

**Closed by kamilmysliwiec** 2017-11-19 19:10 UTC
