### ISSUE TITLE
MaxListenersExceededWarning on socket disconnect event

### ISSUE THREAD

**Issue by cheng38552** [nestjs/nest#14087] opened 2024-10-24 06:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

This problem seems to have not been fixed yet on 10.4.5 version

Multiple gateways will still cause the disconnect event to be registered multiple times

can be found
In a gateway that does not subscribe to message, disconnect will only be registered once.
If there is a gateway that subscribes to messages (no matter how many messages are subscribed), disconnect will be registered twice.

So basically 5 gateways containing subscription messages will appear
"MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 13 listeners added to [Socket]. MaxListeners is 12. Use emitter disconnect.setMaxListeners() to increase limit " problem

### Minimum reproduction code

no

### Expected behavior

No matter how many gateways there are, they will not trigger "MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 13 listeners added to [Socket]. MaxListeners is 12. Use emitter disconnect.setMaxListeners() to increase limit " problem

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.4.5

### Packages versions

```json
 "@nestjs/axios": "^3.1.0",
        "@nestjs/common": "^10.4.6",
        "@nestjs/config": "^3.3.0",
        "@nestjs/core": "^10.4.6",
        "@nestjs/mapped-types": "^2.0.5",
        "@nestjs/platform-express": "^10.4.6",
        "@nestjs/platform-socket.io": "^10.4.6",
        "@nestjs/sequelize": "^10.0.1",
        "@nestjs/websockets": "^10.4.6",
        "@stdlib/random": "^0.3.1",
        "@stdlib/stdlib": "^0.3.0",
        "@stdlib/types": "^0.4.1",
        "@types/i18next": "^13.0.0",
        "@types/luxon": "^3.4.2",
        "axios": "^1.7.2",
        "bh-core": "*",
        "class-transformer": "^0.5.1",
        "class-validator": "^0.14.1",
        "decimal.js": "^10.4.3",
        "i18next": "^23.12.1",
        "i18next-fs-backend": "^2.3.1",
        "luxon": "^3.4.4",
        "mariadb": "^3.3.1",
        "microtime": "^3.1.1",
        "php-serialize": "^4.1.1",
        "proxy-addr": "^2.0.7",
        "redis": "^4.6.15",
        "reflect-metadata": "^0.2.0",
        "rxjs": "^7.8.1",
        "sequelize": "^6.37.3",
        "sequelize-typescript": "^2.1.6",
        "socket.io-client": "^4.7.5"
```

### Node.js version

20.15.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by cheng38552** [comment] 2024-10-24 06:11
#7249

**Comment by kamilmysliwiec** [comment] 2024-10-24 08:16
Duplicate of https://github.com/nestjs/nest/issues/7249

**Closed by kamilmysliwiec** 2024-10-24 08:16 UTC
Labels: needs triage
