### ISSUE TITLE
Can't overrideProvider with any mock in e2e tests

### ISSUE THREAD

**Issue by Christo676** [nestjs/nest#2303] opened 2019-05-30 11:11 UTC
## Current behavior
I tried 3 librairies for mocking a dependency X: Sinon, Typemoq and Ts-Mockito.
When I'm using the @nestjs/testing module to create a testing module and I want to override a provider, the @nestjs/testing doesn't work with all 3 mocking librairies. It wont boot. Out of the 3, only sinon's mock works.

## Input Code
this is a repository that reproduce the problem.
https://github.com/Christo676/nestjs-e2e-mock

```ts
import * as request from 'supertest';
import { Test } from '@nestjs/testing';
import { INestApplication } from '@nestjs/common';
import { AppModule } from '@main/app.module';
import * as sinon from 'sinon';
// import * as TypeMoq from 'typemoq';
import { SomeDependency } from '@main/provider/some-dependency';
import { SinonStubbedInstance } from 'sinon';
// import {instance, mock, when} from 'ts-mockito';

describe('Actuator', (): void => {
    let app: INestApplication;
    //Sinon
    let mockedSomeDependency: SinonStubbedInstance<SomeDependency>;

    //Typemoq
    // let mockedSomeDependency: TypeMoq.IMock<SomeDependency>;

    //Ts-Mockito
    // let mockedSomeDependency: SomeDependency;
    // let instanceSomeDependency: SomeDependency;

    beforeAll(
        async (): Promise<void> => {
            //Sinon
            mockedSomeDependency = sinon.createStubInstance(SomeDependency);
            mockedSomeDependency.getHelloWorld.returns(Promise.resolve('hello nestjs'));

            //Typemoq
            // mockedSomeDependency = TypeMoq.Mock.ofType<SomeDependency>();
            // mockedSomeDependency.setup((someDependency): Promise<string> => someDependency.getHelloWorld()).returns(async () => 'hello nestjs');

            //Ts-Mockito
            // mockedSomeDependency = mock(SomeDependency);
            // when(mockedSomeDependency.getHelloWorld()).thenReturn(Promise.resolve('hello nestjs'));
            // instanceSomeDependency = instance(mockedSomeDependency);

            const module = await Test.createTestingModule({
                imports: [AppModule]
            })
                //Sinon
                .overrideProvider('dependency')
                .useValue(mockedSomeDependency)

                //Typemoq
                //     .overrideProvider('dependency')
                //     .useValue(mockedSomeDependency.object)

                //Ts-Mockito
                //     .overrideProvider('dependency')
                //     .useValue(instanceSomeDependency)
                .compile();

            app = module.createNestApplication();
            await app.init();
        }
    );

    afterAll(
        async (): Promise<void> => {
            await app.close();
        }
    );

    it('should return hello nestjs instead of hello world', async (): Promise<Test> => {
        return await request
            .agent(app.getHttpServer())
            .get('/api/v1/test/greet')
            .expect(200)
            .expect('hello nestjs');
    });
});

```

## Expected behavior
I expect the NestJs testing module to take in all mocks and to override the provider targeted.

## Environment

<pre><code>
Nest version: 6.2.4
 
For Tooling issues:
- Node version: v11.14.0
- Platform:  Windows 10

Others:
IDE: IntelliJ Ultimate 2019
</code></pre>

**Comment by kamilmysliwiec** [comment] 2019-05-30 12:02
Just to confirm that I properly understand your issue. Is `sinon` actually working well, whereas other ones don't work at all?

**Comment by Christo676** [comment] 2019-05-30 12:04
Exactly

**Comment by kamilmysliwiec** [comment] 2019-06-05 09:51
I'm not sure if this issue is really related to Nest ecosystem. If sinon actually works fine, there is no reason for other ones to behave differently. We have recently fixed one issue with `override` (6.3.0 release), could you check if it fixed your issue?

**Comment by Christo676** [comment] 2019-06-06 02:53
I will update my project tomorrow and see if it fixes the problem. I will let you know.

**Comment by Christo676** [comment] 2019-06-09 19:27
I updated my repository with the latest version (6.3.1) and it did't change anything. Only sinon mocks work.

**Comment by mbecker16** [comment] 2019-06-18 00:10
I have this same problem using ts-mockito

**Comment by kamilmysliwiec** [comment] 2019-07-02 07:50
Hi @Christo676,
It seems that there is some weird issue with Proxies & Jest & NestJS & mocking libraries & and `Promise.all()` used at the same time (jest just hangs out).

There is a very simple workaround for this though:
```typescript
//Typemoq
//.overrideProvider('dependency')
//.useValue(Object.assign({}, mockedSomeDependency.object))

//Ts-Mockito
.overrideProvider('dependency')
.useValue(Object.assign({}, instanceSomeDependency))
```
(add `Object.assign()`)

**Closed by kamilmysliwiec** 2019-07-02 07:50 UTC
Labels: needs triage

**Comment by Christo676** [comment] 2019-07-02 12:11
Event if there is a workaround, why do you close this issue? It is still an issue! Why don`t you guys implements a solution or put the workaround in your librairy so the rest of the world don`t have to?

**Comment by kamilmysliwiec** [comment] 2019-07-02 12:12
This issue is not caused by NestJS.

**Comment by Christo676** [comment] 2019-07-02 12:20
Fine it is not cause by NestJs, but it affects the user experience about NestJs. If there was an issue with the integration between NestJs and Express or NestJs and Fastify, I'm pretty sure you guys would do stuff to make it work which will lead to better user experience and better community adoption, even though its not NestJs fault. I believe this scenario is the same. Don't get me wrong, I love what you guys do and I appreciate it. That is why I would like to see that product being more adopted.

**Comment by kamilmysliwiec** [comment] 2019-07-02 12:25
Hardcoding additional checks if `Proxy` object has been created by either `ts-mockito` or `typemoq` sounds quite strange. I'd love to have better user experience with every existing mocking library, but in this case, we'd have to tie the `core` package to 3rd-party libraries.

**Comment by Christo676** [comment] 2019-07-02 12:28
Correct me if i'm wrong but Proxy is a core object of Nodejs, not an object from a third party librairy

**Comment by kamilmysliwiec** [comment] 2019-07-02 12:32
Yes, it is. I didn't say that we'd have to add just  `Proxy` comparison check.

**Comment by Christo676** [comment] 2019-07-02 12:35
I think it would be a good idea and it wouldn't cost much, what do you think?

**Comment by kamilmysliwiec** [comment] 2019-07-02 12:39
Let me clarify. I'm not saying that we would have to add just `Proxy` check, but a check if `Proxy` object has been created by either `ts-mockito` or `typemoq`. Regular proxies are compatible with Nest.

**Comment by Christo676** [comment] 2019-07-02 12:42
Okay you are saying that ``` ts-mockito's  ``` and ``` typemoq's ``` mock are not instance of Proxy? And it is their own object?
