### ISSUE TITLE
The UploadedFile and FileInterceptor doesn't work with Swagger documentation

### ISSUE THREAD

**Issue by alfirin** [nestjs/nest#970] opened 2018-08-14 13:52 UTC
As mentioned [here](https://github.com/nestjs/nest/issues/332) the UploadedFile and FileInterceptor should be documented via Swagger directly.

However it's not the case.

This is my controller:
```
@Post()
    @UseInterceptors(FileInterceptor('filename'))
    async upload(@UploadedFile() file) {
        console.log(file)
    }
```

Swagger is working fine for the others routes, but this is how its displayed

![image](https://user-images.githubusercontent.com/2813035/44095761-e3ce7c54-9fd9-11e8-8374-a0d043261625.png)

What I expected is something like [that supported natively by swagger](https://swagger.io/docs/specification/describing-request-body/file-upload/).

Thanks a lot guys !

**Comment by kamilmysliwiec** [comment] 2018-08-16 12:55
Duplicate of https://github.com/nestjs/swagger/issues/122

**Closed by kamilmysliwiec** 2018-08-16 12:55 UTC
