### ISSUE TITLE
Redis client created with CacheManager (still) does not close when app quits

### ISSUE THREAD

**Issue by EricWVGG** [nestjs/nest#8020] opened 2021-09-02 19:22 UTC
## Current behavior
This is effectively a repeat of https://github.com/nestjs/nest/issues/1621

This problem resurfaced with the 3.x release of `nestjs-command` https://www.npmjs.com/package/nestjs-command, which removed the `{ autoExit }` option. Redis is still running, and prevents CLI commands from wrapping up.

## Input Code
I have a sample repo if that would be helpful.

## Possible Solution
@kamilmysliwiec advised "I'd suggest triggering close in the onModuleDestroy()". I cannot figure out how to reach Redis directly via the cache manager service (also I'm unclear if he even means triggering "close" on Redis, or on a wrapping module, or…?)

I will be happy to update the documentation and post a PR upon solving this issue.

## Environment

<pre><code>
Nest version: 8.0.6
 
For Tooling issues:
- Node version: 16.4.0
- Platform:  Mac
</code></pre>

**Comment by jmcdo29** [comment] 2021-09-02 19:27
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by EricWVGG** [comment] 2021-09-02 19:41
Here you go: https://github.com/EricWVGG/nestjs-redis-issue

**Comment by micalevisk** [comment] 2021-09-02 19:41
> I'd suggest triggering close in the onModuleDestroy()". I cannot figure out how to reach Redis directly via the cache manager service (also I'm unclear if he even means triggering "close" on Redis, or on a wrapping module, or…?)

I think his meant doing something like this: https://github.com/skunight/nestjs-redis/blob/0715fe6809af42ba0996c9d0d30529c887e17fc1/lib/redis-core.module.ts#L53-L61 or this https://github.com/nestjs/typeorm/blob/39924fc369c5e8844c1657e7af7ac61676f9de00/lib/typeorm-core.module.ts#L112-L120 within the parent module that uses the cache manger service (like this https://gist.github.com/kyle-mccarthy/b13e053516ea54a9cc8895a8163b04d9#file-nest-redis-ts-L21)

**Comment by EricWVGG** [comment] 2021-09-02 20:13
Okay, this seems to solve the issue…
```
export class AppModule {
  constructor(
    private connection: Connection,
    @Inject(CACHE_MANAGER) private cacheManager: Cache,
  ) {}
  
  onModuleDestroy() {
    // @ts-ignore
    const client = this.cacheManager.store.getClient()
    client.quit()
  }
}
```
Unfortunately the `cache-manager-redis-store` type definitions don't include getClient. I'll take a peek at that later, and then post a PR if I can get it sorted out.

**Comment by jmcdo29** [comment] 2021-09-02 20:13
This is definitely to do more with the underlying library not having a consistent way to close than with Nest's wrapper keeping the connection open. You can do this and it'll fix the problem

```ts
  async onModuleDestroy() {
    console.log('emit close event here?');
    (this.cacheManager.store as any).getClient().end(true)
  }
```

Kinda janky, but it's due to a prob;em with the types of the underlying library

**Comment by EricWVGG** [comment] 2021-09-02 20:14
jinx!

**Comment by jmcdo29** [comment] 2021-09-02 20:16
Pretty much! I'm going to close this out as it seems there isn't anything to do on the Nest side of things.

One other option would be to create your own redis provider connection and more easily close that with proper intellisense. Then when that closes the cache-manager shouldn't stay open on close. I'll be happy to discuss that approach [in our Discord](https://discord.gg/nestjs) if you're interested

**Closed by jmcdo29** 2021-09-02 20:16 UTC
Labels: needs triage
