### ISSUE TITLE
How do I can change ExceptionHandler on my custom handler?

### ISSUE THREAD

**Issue by Natashkinsasha** [nestjs/nest#4260] opened 2020-03-10 14:24 UTC
I want log "uncaughtException",  "unhandledRejection" and I finded that it make https://github.com/nestjs/nest/blob/master/packages/core/errors/exception-handler.ts. How I can change ExceptionHandler on my custom handler?

**Comment by kamilmysliwiec** [comment] 2020-03-10 14:50
Duplicate of https://github.com/nestjs/nest/issues/3764

**Closed by kamilmysliwiec** 2020-03-10 14:50 UTC
