### ISSUE TITLE
OverwriteModelError: Cannot overwrite `ModelName` model once compiled.

### ISSUE THREAD

**Issue by jeydi243** [nestjs/nest#9797] opened 2022-06-17 20:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I everyone !

I'm building now something and i would like to implement Model inheritance with mongoose and i read [this article](https://docs.nestjs.com/techniques/mongodb#discriminators) to write code.
The expected behavior is the app must be launched but i have this error from Image:
![terminal error](https://user-images.githubusercontent.com/31925905/174397667-5901b9e4-15c9-4afc-8d57-152df9172c33.png)

That is the schema code for all Model(TeacherSchema, StudentSchema, EmployeeSchema):

![teacher schema](https://user-images.githubusercontent.com/31925905/174398172-bceb257b-e3e4-4711-b0c5-08f96d30ba85.png)
![student schema](https://user-images.githubusercontent.com/31925905/174399820-413f7135-1ecd-4bc7-9cb7-77cca159c800.png)
![employee schema](https://user-images.githubusercontent.com/31925905/174398999-bfbd5f4d-0b83-48e0-84f5-51c90436eb63.png)

### Minimum reproduction code

https://github.com/jeydi243/gesi-backend.git

### Steps to reproduce

1. npm install
2. npm run start:dev

### Expected behavior

The application should start without errors.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/mongoose

### NestJS version

8.0.0

### Packages versions

```json
platform-socket.io version : 8.2.4
platform-express version   : 8.2.4
microservices version      : 8.4.2
mapped-types version       : 1.0.1
websockets version         : 8.2.4
schematics version         : 8.0.5
mongoose version           : 9.0.2
passport version           : 8.1.0
swagger version            : 5.2.0
testing version            : 8.2.4
common version             : 8.2.4
config version             : 1.1.6
core version               : 8.2.4
jwt version                : 8.0.0
cli version                : 8.1.6
```

### Node.js version

14.17.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment] 2022-06-17 21:55
looks like your repo https://github.com/jeydi243/gesi-backend isn't public

**Comment by jeydi243** [comment] 2022-06-18 17:02
Sorry. Now it’s public

**Comment by micalevisk** [comment] 2022-06-18 17:44
didn't manage to reproduce your issue. Got this instead:

![image](https://user-images.githubusercontent.com/13461315/174450399-7ae07dfd-45eb-4871-b219-fe25f235d38c.png)

**Comment by jeydi243** [comment] 2022-06-18 18:25
It's a package you can install... But I think it should be in package.json did you run `npm install`?

**Comment by micalevisk** [comment] 2022-06-18 19:12
I followed the steps to reproduce. Please update that or your project to really reproduce your issue.

**Comment by micalevisk** [comment] 2022-06-18 19:52
after installing `temp-dir` and after spending my time figuring out how make your app run _(please write some documentation next time)_, I still didn't manage to reproduce your issue:

<details>

https://user-images.githubusercontent.com/13461315/174454837-d6fce17e-eb30-4f70-a109-be6501d4b106.mp4

</details>

![image](https://user-images.githubusercontent.com/13461315/174455215-df796a95-32fe-4961-8c4c-5a5728af6de1.png)


I won't close this because I didn't try that on Windows but I can't help you unless I could reproduce your issue :disappointed: 

[Why Reproductions are Required](https://antfu.me/posts/why-reproductions-are-required).

---

If you want further support: [Discord](https://discord.gg/nestjs)

**Comment by kamilmysliwiec** [comment] 2022-06-20 06:39
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Closed by kamilmysliwiec** 2022-06-20 06:39 UTC
Labels: needs triage
