### ISSUE TITLE
OnApplicationShutdown cannot finish all async methods

### ISSUE THREAD

**Issue by ecSpl01t** [nestjs/nest#2701] opened 2019-08-03 18:12 UTC
## Bug Report
I'm using onApplicationShutdown for do some of manipulation (async). 
## Current behavior
I've got a msg `Process finished with exit code 1` before finishing.

## Input Code
```ts
const timeout = ms => new Promise(res => setTimeout(res, ms));
@Injectable()
export class LifecycleApp implements OnApplicationShutdown {
    async onApplicationShutdown(signal?: string): Promise<void> {
        console.log('asd');
        await timeout(5000);
        console.log('asd2');
    }
}
```
console
> asd
Process finished with exit code 1

## Expected behavior
All async methods were finished

## Environment
"@nestjs/core": "6.3.1"
 
For Tooling issues:
- Node version: 10
- Platform: Windows

Others:
intellij idea 2019.2

**Comment by BrunnerLivio** [comment] 2019-08-07 11:51
Have you added `app.enableShutdownHooks()` in your `main.ts` as stated in the [docs](https://docs.nestjs.com/fundamentals/lifecycle-events#onapplicationshutdown):

```typescript
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.enableShutdownHooks();
  await app.listen(3000);
}
bootstrap();


```

**Comment by ecSpl01t** [comment] 2019-08-08 18:25
Yes, from my issue you can see, the hook was triggered but didn't finish well (async).
From terminal I got : 
'asd'
'Process finished with exit code 1'
but didn't get console.log('asd2')

**Comment by BrunnerLivio** [comment] 2019-08-08 18:54
@ecSpl01t I could not reproduce your issue when I tried it on my Ubuntu 18.04 and Windows 10 machine. I copy / pasted 1:1 your code and added `app.enableShutdownHooks();` in the `main.ts` as mentioned in my comment above - and it worked. Are you sure the problem is not somewhere else?

**Comment by ecSpl01t** [comment] 2019-08-09 15:41
@BrunnerLivio, thx you for an answer. I spend some time to test this and got this:
![shouldDown](https://user-images.githubusercontent.com/5649365/62790980-880a9380-bacc-11e9-8496-61427d6f394c.png)

So, from this analysis I understood one thing, a problem with `npm run` if I'm using `node server.js` everything is well.

**Comment by BrunnerLivio** [comment] 2019-08-10 14:34
I tried it out with `npm run start` and `node dist/main.ts` and it both worked. Seems like it is not directly related to Nest, therefore I am going to close this issue. Keep me up to date though in case you find out more!

**Closed by BrunnerLivio** 2019-08-10 14:34 UTC
Labels: needs clarification
