### ISSUE TITLE
Creating an ObjectType with a name "Subscription"

### ISSUE THREAD

**Issue by Minishlink** [nestjs/nest#5108] opened 2020-07-17 04:33 UTC
## Current behavior
Using such an object works until you use a resolve property. If you do so, the parent subscription will always be undefined.

## Input Code

```ts
@ObjectType()
export class Subscription {
  @Field(() => ID)
  id!: string;
}

```

## Expected behavior

Either it works completely, or it should throw an error when using this object type name (in typings?)

## Possible Solution
Rename the object type

## Environment

<pre><code>
Nest version: ^6.11.11
 
For Tooling issues:
- Node version: 12  
- Platform:  Mac

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment] 2020-07-17 07:42
Duplicate of https://github.com/nestjs/graphql/issues/934

**Closed by kamilmysliwiec** 2020-07-17 07:42 UTC
Labels: needs triage
