### ISSUE TITLE
MiddlewareConsumer routing is broken

### ISSUE THREAD

**Issue by oleg-yudovich** [nestjs/nest#8108] opened 2021-09-22 07:26 UTC
## Current behavior

The `MiddlewareConsumer` routing is broken when you define home route: `/`
All routes mapped to the same path '/'

## Input Code

Routing module:
```ts
export class RoutingModule implements NestModule {
  configure(consumer: MiddlewareConsumer) {
    consumer
      .apply((req, res) => res.send('hit path /'))
      .forRoutes({ path: '/', method: RequestMethod.GET })
      .apply((req, res) => res.send('hit path /test/app'))
      .forRoutes({ path: '/test/app', method: RequestMethod.GET })
      .apply((req, res) => res.send('hit path /:username'))
      .forRoutes({ path: '/:username', method: RequestMethod.GET });
  }
}
```
App module:
```ts
import { Module } from '@nestjs/common';
import { RoutingModule } from './routing.module';

@Module({
  imports: [RoutingModule],
})
export class AppModule {}

```
Get request to the '/test/app' and  '/:username' prints 'hit path /'
Feels like '/' defined as '*'

## Expected behavior

The `/test/app` and `/:username` routes should be accessible

## Environment

<pre><code>
"@nestjs/common": "^8.0.6",
"@nestjs/core": "^8.0.6",
"@nestjs/platform-express": "^8.0.6"

 
For Tooling issues:
- Node version: 14  
- Platform:  Mac/Linux 

Others:

This issue is not reproduced in NestJS 7.X.X - started in 8.X.X.

This flow works as expected with the Controllers:
</code></pre>
```ts
@Controller()
export class AppController {
  @Get('/')
  homepage(): string {
    return 'hit /';
  }

  @Get('/test/app')
  username(): string {
    return 'hit /test/app';
  }

  @Get('/:username')
  users(): string {
    return 'hit /:username';
  }
}
```

**Comment by jmcdo29** [comment] 2021-09-22 15:31
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by oleg-yudovich** [comment] 2021-09-22 18:16
@jmcdo29 https://github.com/oleg-yudovich/nestjs_8_routing_bug

**Comment by jmcdo29** [comment] 2021-09-22 19:23
Wouldn't this be due to how regex matches work? i.e. if you want to hit just `/` then you either need to bind that last or use `/$` as the regex to signify the end of the string?

**Comment by oleg-yudovich** [comment] 2021-09-23 06:23
@jmcdo29 I don't think you're right. If I register two routes, let's say `/:username` and `/users` so route `/users` should be registered first. When I register just `/` why it should be last? This route regex is not overriding `/something`.
And as I said in the bug description:

1. Is not reproduced with controllers
2. Is not reproduced in NestJs 7.X.X 
3. Is not reproduced with a pure Express server
4. Is not behave like this in any other language and framework

**Comment by Zclhlmgqzc** [comment] 2021-09-23 17:56
> @jmcdo29 I don't think you're right. If I register two routes, let's say `/:username` and `/users` so route `/users` should be registered first. When I register just `/` why it should be last? This route regex is not overriding `/something`.
> And as I said in the bug description:
> 
> 1. Is not reproduced with controllers
> 2. Is not reproduced in NestJs 7.X.X 
> 3. Is not reproduced with a pure Express server
> 4. Is not behave like this in any other language and framework

see #7737
the same with pure express

**Comment by oleg-yudovich** [comment] 2021-09-24 06:53
@Zclhlmgqzc I am running a simple express server (express `4.17.1`):
```js
'use strict'
import express from 'express'

let app = express()

app.get('/', (req, res) => {
  res.send('home')
})

app.get('/about', (req, res) => {
  res.send('about')
})

let server = app.listen(3000, () => {
  console.log(`server running at port http://localhost/${server.address().port}`)
})

```

route http://localhost:3000/about hit `/about`

**Comment by Zclhlmgqzc** [comment] 2021-09-24 07:00
> @Zclhlmgqzc I am running a simple express server (express `4.17.1`,[ the same](https://github.com/nestjs/nest/blob/master/package.json#L61) version used in NestJS):
> ```js
> import express from 'express'
> 
> const app = express()
> 
> app.get('/', (req, res) => {
>   res.send('home')
> })
> 
> app.get('/about', (req, res) => {
>   res.send('about')
> })
> 
> let server = app.listen(3000, () => {
>   console.log(`server running at port http://localhost/${server.address().port}`)
> })
> 
> ```
> 
> route http://localhost:3000/about hit `/about`

app.use != app.get post ...

**Comment by oleg-yudovich** [comment] 2021-09-24 07:01
> > @Zclhlmgqzc I am running a simple express server (express `4.17.1`,[ the same](https://github.com/nestjs/nest/blob/master/package.json#L61) version used in NestJS):
> > ```js
> > import express from 'express'
> > 
> > const app = express()
> > 
> > app.get('/', (req, res) => {
> >   res.send('home')
> > })
> > 
> > app.get('/about', (req, res) => {
> >   res.send('about')
> > })
> > 
> > let server = app.listen(3000, () => {
> >   console.log(`server running at port http://localhost/${server.address().port}`)
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > route http://localhost:3000/about hit `/about`
> 
> app.use != app.get post ...

Yeah, I missed that

**Comment by oleg-yudovich** [comment] 2021-10-05 08:27
@Zclhlmgqzc @kamilmysliwiec FYI - [this](https://github.com/nestjs/nest/releases/tag/v8.0.10) patch does not solve the problem. Please see the example in [this](https://github.com/oleg-yudovich/nestjs_8_routing_bug) simple repo.

**Comment by Zclhlmgqzc** [comment] 2021-10-05 08:32
> @Zclhlmgqzc @kamilmysliwiec FYI - [this](https://github.com/nestjs/nest/releases/tag/v8.0.10) patch does not solve the problem. Please see the example in [this](https://github.com/oleg-yudovich/nestjs_8_routing_bug) simple repo.

forRoutes(AppController) should be equal to [{ path: '/$' }, { path: '/test/app$' }, { path: '/:username$' }]

forRoutes({ path: '/' }, { path: '/test/app' }, { path: '/:username' }) should be not equal to forRoutes(AppController)

so use /$ instead of /

**Comment by oleg-yudovich** [comment] 2021-10-05 08:37
> > @Zclhlmgqzc @kamilmysliwiec FYI - [this](https://github.com/nestjs/nest/releases/tag/v8.0.10) patch does not solve the problem. Please see the example in [this](https://github.com/oleg-yudovich/nestjs_8_routing_bug) simple repo.
> 
> forRoutes(AppController) should be equal to [{ path: '/$' }, { path: '/test/app$' }, { path: '/:username$' }]
> 
> forRoutes({ path: '/' }, { path: '/test/app' }, { path: '/:username' }) should be not equal to forRoutes(AppController)
> 
> so use /$ instead of /
> 
> app.use(/) != app.use(/$)

So is not really a fix to the issue. Now we have different behavior of controllers routing and middleware consumer routing. Is still a bug IMHO

**Comment by oleg-yudovich** [comment] 2021-10-05 08:38
Do we understand why this issue started in NestJS 8 in the first place?

**Comment by Zclhlmgqzc** [comment] 2021-10-05 08:46
> So is not really a fix to the issue. Now we have different behavior of controllers routing and middleware consumer routing. Is still a bug IMHO

I think it's a break change instead of bug
Current behavior:

nest apply(path /) === express use(/)

appy (path /$) === express use(/$) ≈≈ express.all(/)

**Comment by kamilmysliwiec** [comment] 2021-10-05 08:51
To avoid introducing a breaking change, we might need to revert all middleware-specific PRs (all changes since 8.0.5) and wait with that till we release v9 unless you have a better idea @Zclhlmgqzc

**Comment by Zclhlmgqzc** [comment] 2021-10-05 08:58
> To avoid introducing a breaking change, we might need to revert all middleware-specific PRs (all changes since 8.0.5) and wait with that till we release v9 unless you have a better idea @Zclhlmgqzc 

but some breaking change in router-method-factory

apply 7.x path / != 8.x path /
7.x path / GET == 8.x

[7.6.18-router-method-factory](https://github.com/nestjs/nest/blob/v7.6.18/packages/core/helpers/router-method-factory.ts)
[8.0.0-router-method-factory](https://github.com/nestjs/nest/blob/v8.0.0/packages/core/helpers/router-method-factory.ts)

**Comment by Zclhlmgqzc** [comment] 2021-10-05 09:12
@kamilmysliwiec see #7759 

maybe it can fix this problem

```
isRequestMapping default true

forRoutes({ / GET }) === forRoutes({ / isRequestMapping true GET }) ≈≈ express.get(/)


forRoutes({ / isRequestMapping false }) === express.use(/)
```

**Comment by oleg-yudovich** [comment] 2021-10-05 15:57
@kamilmysliwiec @Zclhlmgqzc I found the bug is bigger than described. Actually routing engine through MiddlewareConsumer is completely broken. When you define:
```
export class RoutingModule implements NestModule {
  configure(consumer: MiddlewareConsumer) {
    consumer
      .apply((req, res) => res.send('hit path /test'))
      .forRoutes({ path: '/test', method: RequestMethod.GET })
      .apply((req, res) => res.send('hit path /test/about'))
      .forRoutes({ path: '/test/about', method: RequestMethod.GET });
  }
}
```
The `/test/about` will never be reached - `/test` cathes `/test/about`

**Comment by Zclhlmgqzc** [comment] 2021-10-05 17:06
> The `/test/about` will never be reached - `/test` cathes `/test/about` To avoid route `/x` to catch request of route `/x/y` we now need define route `/x$`

try 

nest-8.0.0/8.0.10:

```
// In this case the /test/about will never be reached also
export class RoutingModule implements NestModule {
  configure(consumer: MiddlewareConsumer) {
    consumer
      .apply((req, res) => res.send('hit path /test'))
      .forRoutes('/test')
      .apply((req, res) => res.send('hit path /test/about'))
      .forRoutes('/test/about');
  }
}
```

nest-7.x:

```
// In this case the /test/about will never be reached also
export class RoutingModule implements NestModule {
  configure(consumer: MiddlewareConsumer) {
    consumer
      .apply((req, res) => res.send('hit path /test'))
      .forRoutes({ path: '/test', method: RequestMethod.ALL })
      .apply((req, res) => res.send('hit path /test/about'))
      .forRoutes({ path: '/test/about', method: RequestMethod.ALL });
  }
}
```

in nest-8.0.5
Express  middleware .use and .all/get/post/delete/put (Router-level middleware)
Fastify middleware  .use only
Use .use instead of the .all(get post...) method ensure the same behavior as fastify

in #8230

new behavior

```
@Controller()
export class AppController {
  @Get('/xx')
  homepage(): string {
    return 'hit /';
  }
}

forRoutes('/xx') === forRoutes(AppController) === forRoutes({ path: '/xx', isRequestMapping: true }) ≈≈ express.all('/xx')

forRoutes({ path: '/xx', isRequestMapping: false }) === express.use('/xx')
```

**Comment by kamilmysliwiec** [comment] 2021-10-06 07:08
> I found the bug is bigger than described. Actually routing engine through MiddlewareConsumer is completely broken. 

@oleg-yudovich this is how fastify/express middleware works. This is not a bug & nor it's "completely broken".

> @kamilmysliwiec see #7759 maybe it can fix this problem

@Zclhlmgqzc this PR won't fix this issue.

To move back to the behavior before 8.0.5, we must revert these PRs you've made:
 - https://github.com/nestjs/nest/pull/7562
 - https://github.com/nestjs/nest/pull/8113
 
 and save them for v9. Would you like to create a revert PR (reverting all changes that were made in the PRs above) and then a PR combining those two so we can have them prepared for v9?

**Comment by kamilmysliwiec** [comment] 2021-10-06 07:37
> What's the problem with the PR #8230 ?

We want to get back to the behavior **before** v8.0.5 to avoid introducing breaking changes.

We can save all improvements you made till v9

**Comment by kamilmysliwiec** [comment] 2021-10-06 07:48
> but if some one else use forRoutes('/xxx') in nest-8 it will use use()

We might need to revert this back to `.all()` as in v7. Still, `@All()` decorator should use `.all()` not `.use()`

**Comment by kamilmysliwiec** [comment] 2021-10-06 11:09
This should be fixed in 8.0.11

**Comment by oleg-yudovich** [comment] 2021-10-06 11:57
Thanks, @kamilmysliwiec, and @Zclhlmgqzc . 
Confirming, the issue is fixed.

**Closed** 2021-10-06 12:04 UTC
Labels: needs triage

**Comment by ianzone** [comment] 2023-03-13 11:57
I'm facing this issue with "@nestjs/core": "^9.3.9", maybe the documentation should emphasize the use of "/$"? cuz intuitively, people would just use "/".
![image](https://user-images.githubusercontent.com/20043230/224694823-10b10a49-4616-436b-a9d5-3d41b44c233c.png)

**Comment by ianzone** [comment] 2023-03-13 13:00
and the behavior of "$" is either consistent, as you can see "/docs$" didn't trigger the DocsMiddleware.
![image](https://user-images.githubusercontent.com/20043230/224708860-b5d90c5b-dd22-4a18-af62-e613e774b799.png)

**Comment by KokoTa** [comment] 2023-08-03 02:36
Have the same issue with nest v10.

"@nestjs/common": "^10.0.0",
"@nestjs/core": "^10.0.0",
"@nestjs/platform-fastify": "^10.0.5",

<img width="454" alt="image" src="https://github.com/nestjs/nest/assets/14892053/1a70e8a0-24dd-4979-914c-deeef0e785a6">

<img width="563" alt="image" src="https://github.com/nestjs/nest/assets/14892053/3e089386-099e-4668-9dff-8d45d5ebacd4">

I must be use `req.originalUrl` to get actual path, `req.url` always return '/'.
This problem is on fastify mode.
