### ISSUE TITLE
Redis Cache is not working with StreamableFile.

### ISSUE THREAD

**Issue by picardplaisimond** [nestjs/nest#10905] opened 2023-01-23 03:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I use the CacheInterceptor with the StreamableFile (and Redis), the browser does not get the right result.

```js
@Get('/sitemap')
@Header('Content-Type', 'application/xml')
@Header('Content-Encoding', 'gzip')
@UseInterceptors(CacheInterceptor)
async getSitemap(): Promise<StreamableFile> {
    const xml = await this.sitemapService.getSitemapBuffer();
    return new StreamableFile(xml);
}
```

StreamableFile object doesn't directly serialize to something that can be easily cached. It cached as a JS object. When the request hit the cache, it spits out the response as a JSON. (and then, we have an encoding issue in the browser).

I'm putting this here, because I know someone else will probably have the same problem in the future. If it's not a bug, it should at least be in the documentation.

### Minimum reproduction code

https://github.com/picardplaisimond/nestjs-cache-redis-problem

### Steps to reproduce

1. `docker-compose up --build -d` (for redis)
2. `npm ci`
3. `npm start:dev`
4. Refresh the page `/sitemap` twice, so it can hit the cache.
5. See the error.

### Expected behavior

When you refresh the page `/sitemap` twice (so it can hit the cache), you will see an encoding error in the browser.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

cache-manager-redis-yet

### Packages versions

```json

```

### Node.js version

9.2.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

### Other

An image of the data inside Redis.
![image](https://user-images.githubusercontent.com/59894191/213962178-7fa37a3b-30f3-417a-9242-b0a0ada6abac.png)

**Comment by micalevisk** [comment] 2023-01-23 03:44
duplicate of #10575

**Closed by micalevisk** 2023-01-23 03:44 UTC
Labels: needs triage
