### ISSUE TITLE
Nest grpc passed object with property named with dash (snake_case) is generating unexpected behavior when translating to grpc proto type  

### ISSUE THREAD

**Issue by KubaJakubowski** [nestjs/nest#5834] opened 2020-11-30 16:23 UTC
## Current behavior
Object sent with grpc service is not translating correctly properties with dash "_" character (snake_case). 
If you create proto file which object have for example "second_name" property divided with dash, 
and you are passing through it object from service which have property named same as in proto file, 
result will be _null_ or empty string.
However, if you pass through service object named with similar name but in camelCase 
(still keeping the proto file in snake_case convention), property from camelCase is successfully passed and 
returns appropriate values.
  

## Input Code
Below is modified example grpc repo, just clone it, install dependencies and run it.
https://github.com/KubaJakubowski/nest-04-grpc-bug-report

For testing purposes i suggest using [TestMace](https://testmace.com).
(Use "Find one" request with " { id: 1}" options ) 
They recently added grpc suppport and it's super easy now to debug connections.

Currently returned data for my code looks like: 
{id: 1, name:"John", second_name:"Sadness"}
(it takes value from "secondName" property)

## Expected behavior
Received should look like this:
{id: 1, name:"John", second_name:"Goldberg"}
(it should take value from "second_name" property)

## Possible Solution
I suppose that there can be some kind of parsing problem.
I also cannot trace where it's exactly generated, but it's probably happening between returning it from service and sending to client.   

## Environment

It was just forked from nest repo, it's the same as master, in case of being behind, i can fast forward it.
So it's applicable to newest versions.
 
For Tooling issues:
- Node version: v12.18.0.
- Platform:  Linux (Kubuntu)

Others:
Kubuntu 20.04,
VisualCode,
npm with Lerna

**Comment by kamilmysliwiec** [comment] 2020-12-01 07:57
Duplicate of https://github.com/nestjs/nest/issues/4917

**Closed by kamilmysliwiec** 2020-12-01 07:57 UTC
Labels: needs triage

**Comment by Mohamedemad4** [comment] 2021-09-16 15:19
hey so I was about to open an issue with this same description but I have found that you guys beat me to it.
i think we should follow [maurolacy's](https://github.com/nestjs/nest/issues/4917#issuecomment-888116945) suggestion in issue #4917  and set `options.loader.keepCase` as `true` by default. I spent 2 days chasing this issue for no good reason just because I didn't read the tiny footnote warning in the documentation. Which is pretty frustrating.

@kamilmysliwiec

**Comment by maurolacy** [comment] 2021-11-17 17:13
GRPC is intended for inter-systems communication. That potentially means or includes different operating systems, different programming languages, and, yes, different case conventions. Forcing a case convention, and silently ignoring fields that do not conform to it is poor engineering.

**Comment by kamilmysliwiec** [comment] 2021-11-18 08:12
@maurolacy please, report this issue in the official gRPC repository because that's where this issue comes from.
